### ISSUE TITLE
Incorrect Result for UPDATE statement

### ISSUE THREAD

**Issue by coldmoutain** [reata/sqllineage#105]
hello reata.when i using sqllineage to analyze the follow SQL .I got a bug.
`UPDATE tablea a
	INNER JOIN (
		SELECT col2
		FROM tableb
		GROUP BY col
	) b
	ON b.col = a.col
SET a.col1 = a.col2 * b.col2
`
that SQL update tablea`s col1  using tableb`s col2 . when i running the SQLLINGAGE it returns tableb as source table but null as target table .in my view the source table should be tableb and the target table should be tablea but not null

**Comment by reata** [comment]
To be honest, when I was designing this package, I was mainly targeting at big data system, like Hive or SparkSQL, where the most commonly used DML is INSERT OVERWRITE.
So yes, the UPDATE statement is definitely ignored during development, not even with test cases covered. And in your case, I agree your expectations are justified. I'll fix it this weekend. 
And plus you're welcome to file a PR if you'd like to try fixing this on your own. I'd be happy to review and merge it.
