### ISSUE TITLE
add supported to SWAP_PARTITIONS_BETWEEN_TABLES 

### ISSUE THREAD

**Issue by davidmr6** [reata/sqllineage#152]
Hi,
the SqlLineage is a very good solution,
if you can add support to the swap function it is a useful,
thanks

**Comment by reata** [comment]
Would you add more info to it:

- The SQL statement you're trying in which the SQLLineage gives you a wrong answer or throws an exception.
- The SQL dialect that supports the feature you requested, better the language specifications. (I did a search, is it for Vertica only as shown in https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/AdministratorsGuide/Partitions/SwappingPartitions.htm)

**Comment by davidmr6** [comment]
> Would you add more info to it:
> 
> * The SQL statement you're trying in which the SQLLineage gives you a wrong answer or throws an exception. And what's your expected or perferred result
> * The SQL dialect that supports the feature you requested, better the language specifications. (I did a search, is it for Vertica only as shown in https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/AdministratorsGuide/Partitions/SwappingPartitions.htm)

Hi ,
The SQLLineage gives me empty list for all object:
"Statements(#): 1
Source Tables:
    
Target Tables:"

I think he just does not know how to recognize it at all,
Attached is a sample query:
SELECT SWAP_PARTITIONS_BETWEEN_TABLES('stg.table1', 'a', 'b', 'dwh.table2')
the source = stg.table1 target = dwh.table2

**Comment by reata** [comment]
I made some further study and this swapping partition from Vertica does look like exchange partition in Hive (https://cwiki.apache.org/confluence/display/Hive/Exchange+Partition). 
And as an FYI, exchange partition is not yet supported in SparkSQL.

I think I need more thought before deciding whether we want this as part of the lineage. And if we decide to do it, then it's better implemented both for Vertica and Hive.

**Comment by reata** [comment]
@davidmr6 Please verify the fix with v1.2.4

**Comment by davidmr6** [comment]
@reata Hi,
its working great job
