### ISSUE TITLE
Parsing 3 part table names

### ISSUE THREAD

**Issue by abcx06** [reata/sqllineage#153]
Hello, is it possible for me to configure sqllineage to understand 3 part (database.schema.table) formatted names? My queries reference all tables in this format but the output is not as expected for them, it's only getting the first 2 parts which are the database and schema. Thanks for any feedback or advice here.

Example vs expected output below:

```
sqllineage -e "CREATE OR REPLACE TABLE dbname.schemaname.tablename AS SELECT o.* FROM dbn.scn.orders o JOIN dbn.scn.users u ON o.id = u.id;"
Statements(#): 1
Source Tables:
    dbn.scn
Target Tables:
    dbname.schemaname
```

Expected source tables:
```
dbn.scn.orders
dbn.scn.users
```

Expected target table:
`dbname.schemaname.tablename`

**Comment by reata** [comment]
Are you using PostgreSQL? Right now sqllineage doesn't support database.schema.table format and it's conflicting with current data model design.

Back when I was using PostgreSQL, I basically treated multiple databases as separate database instance (as if they're running on different server). So would it make sense if SQLLineage gives the result by skipping the database as the following:
```
sqllineage -e "CREATE OR REPLACE TABLE dbname.schemaname.tablename AS SELECT o.* FROM dbn.scn.orders o JOIN dbn.scn.users u ON o.id = u.id;"
Statements(#): 1
Source Tables:
    scn.orders
    scn.users
Target Tables:
    schemaname.tablename
```

**Comment by abcx06** [comment]
Thanks for your response. I'm using Snowflake (and doing cross-DB queries) but it looks like the same format to PostgreSQL. That's an interesting approach, for my use case I want to retain the DB name as well in order to do some downstream string operations on the full names, but I totally understand that this isn't compatible with the current model. I'll keep looking if there are other ways to solve for my use case. I'll go ahead and close this issue. Thank you!

**Comment by reata** [comment]
I actually think this is an interesting use case given Snowflake as a data warehouse solution supports this. Let me check if there's anything I can do. 

I think the bottom line is, for a table named as db.schema.tbl, the last thing we would give end user as full table name is db.schema. No doubt db.schema.tbl as full name is the desired answer, but at least we should try give end user schema.tbl.

**Comment by jlin83** [comment]
FWIW - Redshift has the [same convention](https://docs.aws.amazon.com/redshift/latest/dg/cross-database-overview.html)

**Comment by reata** [comment]
@abcx06 Please try 1.2.4 version. The result should be as expected now:
```bash
$ sqllineage -e "CREATE OR REPLACE TABLE dbname.schemaname.tablename AS SELECT o.* FROM dbn.scn.orders o JOIN dbn.scn.users u ON o.id = u.id;"
Statements(#): 1
Source Tables:
    dbn.scn.orders
    dbn.scn.users
Target Tables:
    dbname.schemaname.tablename
```

Under the hood,  I didn't introduce a new Database model class. Instead, now the Schema can accept database.schema as parameter. So for identifer `dbn.scn.orders`, it's actually schema = "dbn.scn" and table = "orders". Let's see if this approach works.

**Comment by abcx06** [comment]
@reata I've tested it and confirmed it's working as expected, I see the 3 part results now. Thank you so much for your work on this feature. I appreciate your willingness to make this enhancement!
