### ISSUE TITLE
Request: Version 1.3.0 release

### ISSUE THREAD

**Issue by RickardCardell** [reata/sqllineage#162]
Thanks a lot for your handlers-feature: https://github.com/reata/sqllineage/pull/161

This is just a request for having it released so that we can start using it with pip.

**Comment by reata** [comment]
Thanks for reaching out. This handler feature is part of the journey in building a column level lineage tool. 
Any particular reasons you'd like to use the handler feature early?

**Comment by RickardCardell** [comment]
Thanks for your reply.

This is the background:
I've tried to add support for Redshift lineage so I created a Redshift version of `core/handlers/source.py` to handle a few cases.

But instead of forking this repo etc, I preferred a more pluggable solution, where this repo is a dependency and that handlers are injected. 

This can be accomplished by adding a handler that inherits from `NextTokenBaseHandler` (since handlers are collected in https://github.com/reata/sqllineage/blob/master/sqllineage/core/analyzer.py#L69).

So far it was a quite elegant solution, apart from that the original `SourceHandler` were failing and one hacky way to solve it from my repo was to 'monkey patch' it:
```
from sqllineage.core.handlers.source import SourceHandler

def dummy(a, b, c):
    pass

SourceHandler.handle = dummy
```

That's where I am right now. So not so elegant anymore, so maybe forking this repo is the more preferable choice. 
However, it's quite close of being pluggable if we we could disable handlers as well.

**Comment by RickardCardell** [comment]
I forgot to add the main reason I wanted it as a release; I wanted to avoid having it as a `editable` dependency in a Pipfile. 

But it seems to be more in the pipe before the `1.3.0`release so in the mean time I can live with using it as an `editable` dependency.

**Comment by RickardCardell** [comment]
I pulled latest master and a lot of the Redshift specific queries that were previous failing, now works. 
So I will not make use of a custom handler at this point. A few queries fail but I can make a PR for them

**Comment by reata** [comment]
Thank you so much for the backgrounds and insight. I sort of maintain an internal version with monkey patching as well, so yeah, I got your pain.
To make it more extensible is one of my considerations in designing the handler feature. And truth to to told, talking about extensibility, mainly I was thinking about people being able to add new handlers for various SQL dialect to support syntax I'm not aware of. One of the example is #152
As for pluggable, as you said, empowering people to even disable the handler, that wasn't on my mind, not at least in the first place. When implementing this handler feature, I did think of Django middleware design (https://docs.djangoproject.com/en/3.2/topics/http/middleware/#activating-middleware), where user explicitly declare the middleware they want to activate plus framework gives a default setting. If, that was the design choice, then we have disabling power out of box. But in the end, I decide not to lay too much burden to user. With subclass hook, people can just extend the base class, make sure it's imported before calling SQLLineage, that's done. No more extra configuration. Maybe I'll change my mind later. But this is for now.
And it's great to hear that the master can support most of the failing case for Redshift. PR is always welcome. We can look at a release of 1.2.5 after your PR got merged.

**Comment by RickardCardell** [comment]
> With subclass hook, people can just extend the base class, make sure it's imported before calling SQLLineage, that's done. No more extra configuration.

I really like that Idea. The issue that got me was just that the default source-handler threw an exception. Although given the Python newbie I am, there was likely a cleaner work around than disabling the source-handler by a monkey patch :)

I think your solution is very much sufficient and a good way forward and you are doing a gret job bringing features to this repo.

Finally I've made an attempt of bringing more support for Redshift in https://github.com/reata/sqllineage/issues/164

Cheers
