### ISSUE TITLE
not support with?

### ISSUE THREAD

**Issue by wonb168** [reata/sqllineage#182]
sql="""with c1 as (select * from ttt),
c2 as(select * from c1)
select * from (select * from c2 as aa)b"""
result = LineageRunner(sql)
print(result)

Statements(#): 1
Source Tables:
    <default>.ttt
Target Tables:

**Comment by reata** [comment]
WITH Queries (Common Table Expressions) is stored at statement level, but not exposed in lineage summary. Toggle verbose flag to see the statement level lineage:

```python
>>> result = LineageRunner(sql, verbose=True)
>>> print(result)
Statement #1: with c1 as (select * from ttt),c2 as(select * from...
    table read: [Table: <default>.c1, Table: <default>.c2, Table: <default>.ttt]
    table write: []
    table rename: []
    table drop: []
    table intermediate: [Table: <default>.c1, Table: <default>.c2]
==========
Summary:
Statements(#): 1
Source Tables:
    <default>.ttt
Target Tables:

```

What's your expected behavior for with query?

**Comment by reata** [comment]
Close this issue as no further response from end user.
