### ISSUE TITLE
Smarter Column-to-Table Resolution Using Query Context

### ISSUE THREAD

**Issue by reata** [reata/sqllineage#203]
Take this CTE example:
```sql
WITH
  cte1 AS (SELECT a, b FROM table1),
  cte2 AS (SELECT c, d FROM table2)
INSERT OVERWRITE TABLE foo
SELECT b, d FROM cte1 JOIN cte2
WHERE cte1.a = cte2.c;
```

![image](https://user-images.githubusercontent.com/8022906/147260759-aaa7ce7d-3559-4c2c-a3c0-e43ca64e0a19.png)

Although b, d selected is unqualified, we should be able to derive that b comes from table1 and d comes from table2. However, for the moment, we say b and d either come from cte1 or cte2. 

This is not limited for CTE. It applies for subquery, previously defined temporary table/view, etc. All of these give us context to do this smarter column-to-table resolution.

**Comment by TrololoLi** [comment]
I don't think that you need this enhacement. it's a good way to encourage people to write good SQL code.` SELECT b, d` isn't so bad on such a small query, but I've never seen such a query in production. Usually, it's "SELECT 50 columns FROM 50 different tables" and it's pain to read if there is no table name before the column.  So if someone sees that subquery doesn't belong to lineage they could fix their code readability together with the lineage!

**Comment by reata** [comment]
> I don't think that you need this enhacement. it's a good way to encourage people to write good SQL code.` SELECT b, d` isn't so bad on such a small query, but I've never seen such a query in production. Usually, it's "SELECT 50 columns FROM 50 different tables" and it's pain to read if there is no table name before the column. So if someone sees that subquery doesn't belong to lineage they could fix their code readability together with the lineage!

That's true from coding standard's point of view. However we are not living in an ideal world. I saw tons of anti-pattern SQLs along my career in data realm. So I'd like to have this as an enhancement. Column-level lineage without metadata is already a best-effort approach, I feel it's worth the time to add a bit more "effort".

Thanks for your feedback. By the way, if you'd like to enforce good SQL coding standard within your team, like checking if columns are unqualified when joining multiple tables, you can try [sqlfluff](https://github.com/sqlfluff/sqlfluff). In particular, [Rule_L027](https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.core.rules.Rule_L027) is just for this use case.

**Comment by reata** [comment]
One more fun fact, the SQL example provided is actually coming from MySQL official site, what a pity.
https://dev.mysql.com/doc/refman/8.0/en/with.html
