### ISSUE TITLE
MSSQL syntaxes for SELECT isn't supported  

### ISSUE THREAD

**Issue by TrololoLi** [reata/sqllineage#205]
Hi! 
I was trying to parse my MSSQL stored procedures
```
    SELECT
    ISNULL(sst.LocalSalesTerritory, 'Unknown') AS LocalSalesTerritory,
    ISNULL(sst.LocalSalesTeam, 'Unknown') AS LocalSalesTeam,
    EmployeeNumber = ISNULL(sst.EmployeeNumber, 'Unknown'),
    BarterAgencyCode = ISNULL(bag.ClientCode, 'UNKNOWN')
    FROM ....
```
SQLLineage can parse the first two rows, but when I use MSSQL way of selecting with "=" (second two rows) SQLLineage ignores this columns

**Comment by reata** [comment]
Is "EmployeeNumber = ISNULL(sst.EmployeeNumber, 'Unknown')" equal to "ISNULL(sst.EmployeeNumber, 'Unknown') AS EmployeeNumber"?

That's quite a new syntax for me. If you can also add the related SQL syntax reference docs like from Microsoft site, that would be great help.

**Comment by TrololoLi** [comment]
_Is "EmployeeNumber = ISNULL(sst.EmployeeNumber, 'Unknown')" equal to "ISNULL(sst.EmployeeNumber, 'Unknown') AS EmployeeNumber"?_ - Yes 

I went through MSSQL doc and couldn't find anything for this type of aliases. I found some info here though
https://riptutorial.com/sql/example/1264/select-using-column-aliases 
Starting from "A further variation available in MS SQL Server amongst others is <alias> = <column-or-calculation>, for instance:"

**Comment by reata** [comment]
This should be the official docs: https://docs.microsoft.com/en-us/sql/t-sql/language-elements/assignment-operator-transact-sql?view=sql-server-ver15

Since this is not ANSI compatible, I might not put it into high priority issues. I'll take some time later to access the difficulty of implementing this feature.

**Comment by reata** [comment]
After we release v1.4.0 next month, you shall be able to use --dialect=tsql in command line, or in python `LineageRunner(sql, dialect="tsql")` to leverage our new parsing capability and get the correct result.

sample input:
```sql
INSERT INTO FOO
SELECT
    ISNULL(sst.LocalSalesTerritory, 'Unknown') AS LocalSalesTerritory,
    ISNULL(sst.LocalSalesTeam, 'Unknown') AS LocalSalesTeam,
    EmployeeNumber = ISNULL(sst.EmployeeNumber, 'Unknown'),
    BarterAgencyCode = ISNULL(bag.ClientCode, 'UNKNOWN')
FROM sst JOIN bag ON sst.id = bag.id;
```

output:
```
$ sqllineage -f test.sql -l column --dialect=tsql
<default>.foo.barteragencycode <- <default>.bag.clientcode
<default>.foo.employeenumber <- <default>.sst.employeenumber
<default>.foo.localsalesteam <- <default>.sst.localsalesteam
<default>.foo.localsalesterritory <- <default>.sst.localsalesterritory
```
