### ISSUE TITLE
Specify Column Names in Insert Statement

### ISSUE THREAD

**Issue by woshiniuren** [reata/sqllineage#212]
Hi ~  
"insert into aaa(de00001) select name from a;"      for this sql string expect to be <default>.aaa.de00001<- <default>.a.name
but it turns out to be   <default>.aaa.name <- <default>.a.name, is this something wrong ?

**Comment by reata** [comment]
To specify column name in the query is not supported yet. The following also doesn't work:

```sql
create table tab1 (col1 string) AS
select col2 from tab2;

create view tab1 (col1, col2) AS
select col3, col4 from tab2;
```

I'll see what I can do to improve on this.

**Comment by nickhuang1996** [comment]
@reata Sure! Thank you for your explanation!

**Comment by reata** [comment]
This is supported by ansi dialect. Note we won't port it back to default non-validating as sqlparse cannot generate correct AST for this case.
