### ISSUE TITLE
Failed to Parse Source Table From Subquery With More Than One Parenthesis

### ISSUE THREAD

**Issue by reata** [reata/sqllineage#213]
```bash
➜  ~ sqllineage -e "SELECT * FROM ((SELECT * FROM foo)) dt"          
Statements(#): 1
Source Tables:
    <default>.dt
Target Tables:
    
```

Expected source table would be foo.

**Comment by diecrf** [comment]
Not sure if same error, but there is also a problem with column lineage when parenthesis are used

The following query includes `s6` column, but `s5` is missing

```
sqllineage -e "INSERT INTO sch1.target SELECT s1, s2, (s3+s4) AS s5, s3+s4 AS s6 FROM sch0.source" -l column
sch1.target.s1 <- sch0.source.s1
sch1.target.s2 <- sch0.source.s2
sch1.target.s6 <- sch0.source.s3
sch1.target.s6 <- sch0.source.s4
```

I wanted to take a look to the source code before opening the issue, but as it seems related, I've added this comment

Thanks!
