### ISSUE TITLE
Problem with SELECT CAST(CASE WHEN ...END AS DECIMAL(M,N)) AS col_name

### ISSUE THREAD

**Issue by nickhuang1996** [reata/sqllineage#215]
Sorry for this problem, but if statement is like:
SELECT CAST(CASE WHEN ..., 
                               WHEN ...,
                               END AS DECIMAL(M, N)) AS col_name
FROM ...
the result is:
<default>table_name.col_name -> decimal
I don't know how to deal with this statement, or could I cut 'CAST’ function for analysis?

**Comment by reata** [comment]
Sorry for the late reply, been really busy recently.

This should definitely be a bug in dealing with nested column structure. I'll schedule some time next week to fix this. If you're interested, you're also welcome to try.

**Comment by nickhuang1996** [comment]
@reata 
Thanks, I cut the cast function, which is:
cast(case when ... end as decimal(M,N) as col_name -> case case when ... end as col_name.
Then the problem is temporarily fixed.
