### ISSUE TITLE
Source table with DB Name not identified in insert query

### ISSUE THREAD

**Issue by Abhiram98** [reata/sqllineage#218]
```
➜  ~ sqllineage -e "insert into db1.table1 (select * from db2.table2)"

Statements(#): 1
Source Tables:
    
Target Tables:
    db1.table1

```

"db2.table2" is not identified as a source table

**Comment by reata** [comment]
Thanks for reporting this. 

This is somewhat relate to #213 . Let's target at fixing them together.

**Comment by reata** [comment]
I did some investigation, turns out this is a very different issue. 

To start with, using v.1.3.3, the following query works:
```bash
~ sqllineage -e "insert into table1 (select * from db2.table2)"
Statements(#): 1
Source Tables:
    db2.table2
Target Tables:
    <default>.table1
```

The reason is that `sqlparse` generate very different AST for the two queries:
```python
In [1]: import sqlparse

In [2]: sqlparse.parse("INSERT INTO db1.table1 (SELECT * FROM db2.table2)")[0].tokens
Out[2]: 
[<DML 'INSERT' at 0x7F56348C6D08>,
 <Whitespace ' ' at 0x7F563489DE28>,
 <Keyword 'INTO' at 0x7F563489DE88>,
 <Whitespace ' ' at 0x7F563489DDC8>,
 <Identifier 'db1.ta...' at 0x7F5634873840>]

In [3]: sqlparse.parse("INSERT INTO table1 (SELECT * FROM db2.table2)")[0].tokens
Out[3]: 
[<DML 'INSERT' at 0x7F5634850D08>,
 <Whitespace ' ' at 0x7F5634850D68>,
 <Keyword 'INTO' at 0x7F5634850CA8>,
 <Whitespace ' ' at 0x7F5634850C48>,
 <Function 'table1...' at 0x7F5634873930>]
```

In theory, both Identifier and Function are wrong under this circumstance. But we had a hack to deal with Function so it works. Guess we might need another hack. 

This will an ugly solution. We really need a better validating parser in the long run.

**Comment by reata** [comment]
Tried to add a new hack but failed. To make it work, we might need to monkey patch the lexer, that is not what I want.

@Abhiram98 Unfortunately I don't have an ETA get this fixed. As a walk around, you can try quote the table names to force the parser to generate a reasonable syntax tree so we get correct result:
```
INSERT INTO "db1"."table1" (SELECT * FROM db2.table2)
```

**Comment by reata** [comment]
An alternative walk-around is to remove the parenthesis. The parsing result is also correct this way.

**Comment by reata** [comment]
See #249 for more details. In short, we'll be able to handle this in v1.4.0
