### ISSUE TITLE
Multi-table queries cannot display column names

### ISSUE THREAD

**Issue by 3wjs** [reata/sqllineage#242]
sql like :
SELECT t1.id,
       t2.uid
FROM   t1,
       t2
WHERE  t1.id = t2.id
when i use like :sqllineage -e "sql" -l column
the result is nothing,but  tables name is ok ,Can this issue be solved? 
thanks for your work ：）

**Comment by reata** [comment]
In the sense of a lineage, there must be source and target. 
For table level lineage, we can output source and target separately at SQL statement level. 
But for column level lineage, it's a path from source column to target column, with optional subquery column in between. Put it in another word, we don't support SELECT statement for column lineage. Changing this to INSERT INTO or INSERT OVERWRITE, you'll see the correct column lineage.

If you're requesting for a support of this feature, please let me know the reason why you need it, so I can prioritize this issue.

**Comment by reata** [comment]
Close this issue as no update for more than 6 months.
