### ISSUE TITLE
error in parseing my complex sql column lineage [bug]

### ISSUE THREAD

**Issue by wonb168** [reata/sqllineage#246]
my complex sql:
`WITH protect AS (
            SELECT product_code, color_code, stockorg_sk
                , is_new_skc                            -- 新品保护期
                , is_new_store                          -- 新店保护期
                , has_in AS size_has_in                 -- 近期调入sku保护
                , not_out                               -- 门店商品异常状态（不能调出）
                , true AS forbidden_flag               -- 是否来源all_data
                , no_included_model                     -- 未进入补调模型
                , is_trans_empty_bef                    -- 最后一件库存不是卖出而是调出
                , case when has_ms = 0 then true else false end as has_ms  --是否有主码 -转为 款店组合没有主码
                --, has_ms                                -- 款店组合没有主码
                , not_trans_out AS size_not_trans_out   -- 不允许调拨出
                , not_trans_in AS size_not_trans_in     -- 不允许调拨入
                , not_rep_in AS size_not_rep_in         -- 不允许补货入
                , day_date
            FROM tenant_bsgj_biz.gto_skc_org_label
        ), store_warehouse as (
            select stockorg_sk, org_flag from tenant_bsgj_edw.dim_stockorg
            group by stockorg_sk, org_flag
        )
           , ori AS(
            SELECT
                color_code, model_allot_in_org_code, brand_name, modify_status, remark, scene_name, ra_source, skc_sk, biz_action_template_code, model_allot_out_org_sk, commit_status, scene_code, size_group_code, human_allot_in_org_code, human_allot_out_org_code, class_longcode, model_allot_in_org_sk, document_code, model_allot_out_org_code, brand_code, product_code, human_allot_in_org_sk, human_allot_out_org_sk, order_id, day_date, org_name, biz_action_template_name, skc_code, human_allot_in_org_name, human_allot_out_org_name, in_org_last_7days_sales_qty, out_org_last_7days_sales_qty, in_org_last_7_14days_sales_qty, out_org_last_7_14days_sales_qty, in_org_total_sales_qty, out_org_total_sales_qty, human_ra_qty, national_skc_last_7days_sales_qty, national_skc_last_7_14days_sales_qty, national_skc_total_sales_qty
            FROM tenant_bsgj_biz.rst_ra_skc_org_detail sod
            left join store_warehouse as in_sw on in_sw.stockorg_sk::text = sod.human_allot_in_org_sk
            left join store_warehouse as out_sw on out_sw.stockorg_sk::text = sod.human_allot_out_org_sk
            WHERE
            -- 权限筛选 和 权限控制
            CASE WHEN ra_source = 3 OR (in_sw.org_flag = 2 AND out_sw.org_flag = 2) THEN
                (human_allot_in_org_sk IN ('10069913','10181965'))
                ELSE
                    (human_allot_in_org_sk IN ('10069913','10181965'))
                END
            and (skc_code in ('DZ9345') or skc_code is null)
               and day_date = '2021-12-27'
        )
           , t_model as (
            SELECT
                ori.color_code, ori.model_allot_in_org_code, ori.brand_name, ori.modify_status, ori.remark, ori.scene_name, ori.ra_source, ori.skc_sk, ori.biz_action_template_code, ori.model_allot_out_org_sk, ori.commit_status, ori.scene_code, ori.size_group_code, ori.human_allot_in_org_code, ori.human_allot_out_org_code, ori.class_longcode, ori.model_allot_in_org_sk, ori.document_code, ori.model_allot_out_org_code, ori.brand_code, ori.product_code, ori.human_allot_in_org_sk, ori.human_allot_out_org_sk, ori.order_id, ori.day_date, ori.org_name, ori.biz_action_template_name, ori.skc_code, ori.human_allot_in_org_name, ori.human_allot_out_org_name, ori.in_org_last_7days_sales_qty, ori.out_org_last_7days_sales_qty, ori.in_org_last_7_14days_sales_qty, ori.out_org_last_7_14days_sales_qty, ori.in_org_total_sales_qty, ori.out_org_total_sales_qty, ori.human_ra_qty, ori.national_skc_last_7days_sales_qty, ori.national_skc_last_7_14days_sales_qty, ori.national_skc_total_sales_qty
            FROM ori WHERE ra_source != 3 -- 3：规则生成
        )
        , t_rule_wh AS (
            SELECT ori.color_code, ori.model_allot_in_org_code, ori.brand_name, ori.modify_status, ori.remark, ori.scene_name, ori.ra_source, ori.skc_sk, ori.biz_action_template_code, ori.model_allot_out_org_sk, ori.commit_status, ori.scene_code, ori.size_group_code, ori.human_allot_in_org_code, ori.human_allot_out_org_code, ori.class_longcode, ori.model_allot_in_org_sk, ori.document_code, ori.model_allot_out_org_code, ori.brand_code, ori.product_code, ori.human_allot_in_org_sk, ori.human_allot_out_org_sk, ori.order_id, ori.day_date, ori.org_name, ori.biz_action_template_name, ori.skc_code, ori.human_allot_in_org_name, ori.human_allot_out_org_name, ori.in_org_last_7days_sales_qty, ori.out_org_last_7days_sales_qty, ori.in_org_last_7_14days_sales_qty, ori.out_org_last_7_14days_sales_qty, ori.in_org_total_sales_qty, ori.out_org_total_sales_qty, ori.human_ra_qty, ori.national_skc_last_7days_sales_qty, ori.national_skc_last_7_14days_sales_qty, ori.national_skc_total_sales_qty
            , t_model.human_allot_in_org_sk AS model_exist
            FROM ori
            LEFT JOIN t_model
                ON ori.human_allot_in_org_sk = t_model.human_allot_in_org_sk
                AND ori.skc_sk = t_model.skc_sk
                AND (ori.document_code is null and t_model.document_code is null)
            LEFT JOIN store_warehouse as sw_in
                on sw_in.stockorg_sk::text = ori.human_allot_in_org_sk
            LEFT JOIN store_warehouse as sw_out
                on sw_out.stockorg_sk::text = ori.human_allot_out_org_sk
            WHERE ori.ra_source = 3 -- 3: 规则生成
                AND sw_in.org_flag = 2 and sw_out.org_flag isnull
        )
        , t_rule_wh_filter AS (
            SELECT DISTINCT ON (human_allot_in_org_sk, skc_sk,  coalesce(document_code, ''))
                color_code, model_allot_in_org_code, brand_name, modify_status, remark, scene_name, ra_source, skc_sk, biz_action_template_code, model_allot_out_org_sk, commit_status, scene_code, size_group_code, human_allot_in_org_code, human_allot_out_org_code, class_longcode, model_allot_in_org_sk, document_code, model_allot_out_org_code, brand_code, product_code, human_allot_in_org_sk, human_allot_out_org_sk, order_id, day_date, org_name, biz_action_template_name, skc_code, human_allot_in_org_name, human_allot_out_org_name, in_org_last_7days_sales_qty, out_org_last_7days_sales_qty, in_org_last_7_14days_sales_qty, out_org_last_7_14days_sales_qty, in_org_total_sales_qty, out_org_total_sales_qty, human_ra_qty, national_skc_last_7days_sales_qty, national_skc_last_7_14days_sales_qty, national_skc_total_sales_qty FROM t_rule_wh WHERE model_exist IS NULL)
        , store_org_sks as ( -- 当前存在门店
            SELECT model_allot_out_org_sk AS org_sk FROM  t_model
            UNION ALL SELECT model_allot_in_org_sk AS org_sk FROM  t_model
            UNION ALL SELECT human_allot_out_org_sk AS org_sk FROM  t_model
            UNION ALL SELECT human_allot_in_org_sk AS org_sk FROM  t_model
        )
        , relation as ( -- 发货关系
            SELECT DISTINCT dsr.send_stockorg_sk::text AS relation_org_sk
            FROM store_org_sks sos
            INNER JOIN     tenant_bsgj_edw.dim_circulation_relationship dsr
            ON sos.org_sk = dsr.receive_stockorg_sk::text
            UNION
            SELECT DISTINCT dsr.receive_stockorg_sk::text AS relation_org_sk
            FROM store_org_sks sos
            INNER JOIN     tenant_bsgj_edw.dim_circulation_relationship dsr
            ON sos.org_sk = dsr.send_stockorg_sk::text
        )
        , t_rule AS (
            SELECT ori.color_code, ori.model_allot_in_org_code, ori.brand_name, ori.modify_status, ori.remark, ori.scene_name, ori.ra_source, ori.skc_sk, ori.biz_action_template_code, ori.model_allot_out_org_sk, ori.commit_status, ori.scene_code, ori.size_group_code, ori.human_allot_in_org_code, ori.human_allot_out_org_code, ori.class_longcode, ori.model_allot_in_org_sk, ori.document_code, ori.model_allot_out_org_code, ori.brand_code, ori.product_code, ori.human_allot_in_org_sk, ori.human_allot_out_org_sk, ori.order_id, ori.day_date, ori.org_name, ori.biz_action_template_name, ori.skc_code, ori.human_allot_in_org_name, ori.human_allot_out_org_name, ori.in_org_last_7days_sales_qty, ori.out_org_last_7days_sales_qty, ori.in_org_last_7_14days_sales_qty, ori.out_org_last_7_14days_sales_qty, ori.in_org_total_sales_qty, ori.out_org_total_sales_qty, ori.human_ra_qty, ori.national_skc_last_7days_sales_qty, ori.national_skc_last_7_14days_sales_qty, ori.national_skc_total_sales_qty
                , r_out.relation_org_sk AS human_out_sk
                , t_model.human_allot_in_org_sk AS model_exist
                FROM ori
                LEFT JOIN relation r_out ON r_out.relation_org_sk = ori.human_allot_in_org_sk
                LEFT JOIN t_model
                    ON ori.human_allot_in_org_sk = t_model.human_allot_in_org_sk
                    AND ori.skc_sk = t_model.skc_sk
                    AND ((ori.document_code is null and t_model.document_code is null)
                        OR ori.document_code = t_model.document_code)
                LEFT JOIN store_warehouse as sw_in
                    on sw_in.stockorg_sk::text = ori.human_allot_in_org_sk
                LEFT JOIN store_warehouse as sw_out
                    on sw_out.stockorg_sk::text = ori.human_allot_out_org_sk
            WHERE ori.ra_source = 3 -- 3: 规则生成
                AND (sw_in.org_flag != 2 or sw_in.org_flag isnull)
        )
        , t_rule_null_to_store_filter AS (
            SELECT DISTINCT ON (human_allot_in_org_sk, skc_sk,  coalesce(document_code, ''))
                color_code, model_allot_in_org_code, brand_name, modify_status, remark, scene_name, ra_source, skc_sk, biz_action_template_code, model_allot_out_org_sk, commit_status, scene_code, size_group_code, human_allot_in_org_code, human_allot_out_org_code, class_longcode, model_allot_in_org_sk, document_code, model_allot_out_org_code, brand_code, product_code, human_allot_in_org_sk, human_allot_out_org_sk, order_id, day_date, org_name, biz_action_template_name, skc_code, human_allot_in_org_name, human_allot_out_org_name, in_org_last_7days_sales_qty, out_org_last_7days_sales_qty, in_org_last_7_14days_sales_qty, out_org_last_7_14days_sales_qty, in_org_total_sales_qty, out_org_total_sales_qty, human_ra_qty, national_skc_last_7days_sales_qty, national_skc_last_7_14days_sales_qty, national_skc_total_sales_qty FROM t_rule WHERE model_exist IS NULL AND human_out_sk IS NOT NULL
                and human_allot_in_org_sk is not null
        )
        , t_rule_wh_to_null_filter AS (
            SELECT DISTINCT ON (human_allot_out_org_sk, skc_sk,  coalesce(document_code, ''))
                color_code, model_allot_in_org_code, brand_name, modify_status, remark, scene_name, ra_source, skc_sk, biz_action_template_code, model_allot_out_org_sk, commit_status, scene_code, size_group_code, human_allot_in_org_code, human_allot_out_org_code, class_longcode, model_allot_in_org_sk, document_code, model_allot_out_org_code, brand_code, product_code, human_allot_in_org_sk, human_allot_out_org_sk, order_id, day_date, org_name, biz_action_template_name, skc_code, human_allot_in_org_name, human_allot_out_org_name, in_org_last_7days_sales_qty, out_org_last_7days_sales_qty, in_org_last_7_14days_sales_qty, out_org_last_7_14days_sales_qty, in_org_total_sales_qty, out_org_total_sales_qty, human_ra_qty, national_skc_last_7days_sales_qty, national_skc_last_7_14days_sales_qty, national_skc_total_sales_qty FROM t_rule WHERE model_exist IS NULL AND human_out_sk IS NOT NULL
                and human_allot_in_org_sk is null
        )
        , t AS (
            SELECT
                order_id, day_date, scene_name, org_name, biz_action_template_name, skc_code, human_allot_in_org_code, human_allot_in_org_name, size_group_code, in_org_last_7days_sales_qty, in_org_last_7_14days_sales_qty, in_org_total_sales_qty, human_allot_out_org_code, human_allot_out_org_name, human_ra_qty, remark, national_skc_last_7days_sales_qty, national_skc_last_7_14days_sales_qty, national_skc_total_sales_qty, color_code, model_allot_in_org_code, brand_name, modify_status, ra_source, skc_sk, biz_action_template_code, model_allot_out_org_sk, commit_status, scene_code, class_longcode, model_allot_in_org_sk, document_code, model_allot_out_org_code, brand_code, product_code, human_allot_in_org_sk, human_allot_out_org_sk
            FROM t_model
            UNION ALL
            SELECT
                order_id, day_date, scene_name, org_name, biz_action_template_name, skc_code, human_allot_in_org_code, human_allot_in_org_name, size_group_code, in_org_last_7days_sales_qty, in_org_last_7_14days_sales_qty, in_org_total_sales_qty, human_allot_out_org_code, human_allot_out_org_name, human_ra_qty, remark, national_skc_last_7days_sales_qty, national_skc_last_7_14days_sales_qty, national_skc_total_sales_qty, color_code, model_allot_in_org_code, brand_name, modify_status, ra_source, skc_sk, biz_action_template_code, model_allot_out_org_sk, commit_status, scene_code, class_longcode, model_allot_in_org_sk, document_code, model_allot_out_org_code, brand_code, product_code, human_allot_in_org_sk, human_allot_out_org_sk
            FROM t_rule_null_to_store_filter
            UNION ALL
            SELECT
                order_id, day_date, scene_name, org_name, biz_action_template_name, skc_code, human_allot_in_org_code, human_allot_in_org_name, size_group_code, in_org_last_7days_sales_qty, in_org_last_7_14days_sales_qty, in_org_total_sales_qty, human_allot_out_org_code, human_allot_out_org_name, human_ra_qty, remark, national_skc_last_7days_sales_qty, national_skc_last_7_14days_sales_qty, national_skc_total_sales_qty, color_code, model_allot_in_org_code, brand_name, modify_status, ra_source, skc_sk, biz_action_template_code, model_allot_out_org_sk, commit_status, scene_code, class_longcode, model_allot_in_org_sk, document_code, model_allot_out_org_code, brand_code, product_code, human_allot_in_org_sk, human_allot_out_org_sk
            FROM t_rule_wh_to_null_filter
            UNION ALL
            SELECT
                order_id, day_date, scene_name, org_name, biz_action_template_name, skc_code, human_allot_in_org_code, human_allot_in_org_name, size_group_code, in_org_last_7days_sales_qty, in_org_last_7_14days_sales_qty, in_org_total_sales_qty, human_allot_out_org_code, human_allot_out_org_name, human_ra_qty, remark, national_skc_last_7days_sales_qty, national_skc_last_7_14days_sales_qty, national_skc_total_sales_qty, color_code, model_allot_in_org_code, brand_name, modify_status, ra_source, skc_sk, biz_action_template_code, model_allot_out_org_sk, commit_status, scene_code, class_longcode, model_allot_in_org_sk, document_code, model_allot_out_org_code, brand_code, product_code, human_allot_in_org_sk, human_allot_out_org_sk
            FROM t_rule_wh_filter
        )
        , res AS (
        SELECT
            p.is_new_skc, p.is_new_store, p.size_has_in, p.not_out, p.forbidden_flag, p.no_included_model,
            p.is_trans_empty_bef, p.has_ms, p.size_not_trans_out, p.size_not_trans_in, p.size_not_rep_in,
            p2.is_new_skc AS is_new_skc_in, p2.is_new_store AS is_new_store_in, p2.size_has_in AS size_has_in_in,
            p2.not_out AS not_out_in, p2.forbidden_flag AS forbidden_flag_in,
            p2.no_included_model AS no_included_model_in, p2.is_trans_empty_bef AS is_trans_empty_bef_in,
            p2.has_ms AS has_ms_in, p2.size_not_trans_out AS size_not_trans_out_in,
            p2.size_not_trans_in AS size_not_trans_in_in, p2.size_not_rep_in AS size_not_rep_in_in,

        t.order_id, t.day_date, t.scene_name, t.org_name, t.biz_action_template_name, t.skc_code, t.human_allot_in_org_code, t.human_allot_in_org_name, t.size_group_code, t.in_org_last_7days_sales_qty, t.in_org_last_7_14days_sales_qty, t.in_org_total_sales_qty, t.human_allot_out_org_code, t.human_allot_out_org_name, t.human_ra_qty, t.remark, t.national_skc_last_7days_sales_qty, t.national_skc_last_7_14days_sales_qty, t.national_skc_total_sales_qty, t.color_code, t.model_allot_in_org_code, t.brand_name, t.modify_status, t.ra_source, t.skc_sk, t.biz_action_template_code, t.model_allot_out_org_sk, t.commit_status, t.scene_code, t.class_longcode, t.model_allot_in_org_sk, t.document_code, t.model_allot_out_org_code, t.brand_code, t.product_code, t.human_allot_in_org_sk, t.human_allot_out_org_sk

        FROM t
        LEFT JOIN protect p ON p.product_code = t.product_code
            AND p.color_code = t.color_code
            AND p.stockorg_sk::text = t.human_allot_out_org_sk
            AND p.day_date = '2021-12-27'
        LEFT JOIN protect p2 ON p2.product_code = t.product_code
            AND p2.color_code = t.color_code
            AND p2.stockorg_sk::text = t.human_allot_in_org_sk
            AND p2.day_date = '2021-12-27'

        LEFT JOIN tenant_bsgj_biz.gto_skc_org_feature AS skc
            ON t.skc_sk::integer=skc.skc_sk
            AND t.human_allot_in_org_sk::integer=skc.org_sk
            AND skc.day_date='2021-12-27'

        LEFT JOIN tenant_bsgj_biz.gto_skc_org_feature as out
            ON t.skc_sk::integer=out.skc_sk
            AND t.human_allot_out_org_sk::integer = out.org_sk
            AND out.day_date='2021-12-27'

        LEFT JOIN tenant_bsgj_biz.gto_skc_org_feature AS i_n
            ON t.skc_sk::integer=i_n.skc_sk
            AND t.human_allot_in_org_sk::integer=i_n.org_sk
            AND i_n.day_date='2021-12-27'

        )
         SELECT p.is_new_skc, p.is_new_store, p.size_has_in, p.not_out, p.forbidden_flag, p.no_included_model
         FROM res
         order by national_skc_last_7days_sales_qty->'total' desc nulls last, national_skc_last_7_14days_sales_qty->'total' desc nulls last, national_skc_total_sales_qty->'total' desc nulls last, skc_code asc nulls first, in_org_last_7days_sales_qty->'total' desc nulls last, in_org_last_7_14days_sales_qty->'total' desc nulls last, in_org_total_sales_qty->'total' desc nulls last
`
image show subquery relation is alone, but it is used for many times , and into subquery rule's column

**Comment by reata** [comment]
First of all, we don't officially support SELECT only statement. So it's better you append an DML part at the beginning of your query, for example **CREATE VIEW test AS**
```sql
WITH ...
CREATE VIEW test AS
SELECT p.is_new_skc, p.is_new_store, p.size_has_in, p.not_out, p.forbidden_flag, p.no_included_model
     FROM res
     order by national_skc_last_7days_sales_qty->'total' desc nulls last, national_skc_last_7_14days_sales_qty->'total' desc nulls last, national_skc_total_sales_qty->'total' desc nulls last, skc_code asc nulls first, in_org_last_7days_sales_qty->'total' desc nulls last, in_org_last_7_14days_sales_qty->'total' desc nulls last, in_org_total_sales_qty->'total' desc nulls last
```

Secondly, I don't think this syntax is valid. For columns selected in the main query, `p.is_new_skc, p.is_new_store, p.size_has_in, p.not_out, p.forbidden_flag, p.no_included_model`, what is p alias for? I don't see it as an alias or CTE name. Please provide for info. Thanks.

**Comment by reata** [comment]
Close this issue as no update for more than 6 months.
