### ISSUE TITLE
[bug]column lineage some column lost

### ISSUE THREAD

**Issue by wonb168** [reata/sqllineage#248]
`insert into edw.fct_stock_move
(
    doc_id, doc_time, doc_source, sku_sk, send_stockorg_sk, receive_stockorg_sk, move_type_code, origin_type_code, send_qty,
    receive_qty, send_time, receive_time, receive_date, etl_time, send_date
)
select
    doc_id, doc_time, doc_source, sku_sk, send_stockorg_sk, receive_stockorg_sk, move_type_code, origin_type_code, send_qty,
    receive_qty, send_time, receive_time, receive_date, current_timestamp etl_time, send_date
from tmp_stock_move`
get_column_lineage(exclude_subquery=False)
last two columns **etl_time and send_date are lost**, maybe current_timestamp  cost this problem?

result:
(Column: <default>.tmp_stock_move.doc_id, Column: edw.fct_stock_move.doc_id)
(Column: <default>.tmp_stock_move.doc_source, Column: edw.fct_stock_move.doc_source)
(Column: <default>.tmp_stock_move.doc_time, Column: edw.fct_stock_move.doc_time)
(Column: <default>.tmp_stock_move.move_type_code, Column: edw.fct_stock_move.move_type_code)
(Column: <default>.tmp_stock_move.origin_type_code, Column: edw.fct_stock_move.origin_type_code)
(Column: <default>.tmp_stock_move.receive_date, Column: edw.fct_stock_move.receive_date)
(Column: <default>.tmp_stock_move.receive_qty, Column: edw.fct_stock_move.receive_qty)
(Column: <default>.tmp_stock_move.receive_stockorg_sk, Column: edw.fct_stock_move.receive_stockorg_sk)
(Column: <default>.tmp_stock_move.receive_time, Column: edw.fct_stock_move.receive_time)
(Column: <default>.tmp_stock_move.send_qty, Column: edw.fct_stock_move.send_qty)
(Column: <default>.tmp_stock_move.send_stockorg_sk, Column: edw.fct_stock_move.send_stockorg_sk)
(Column: <default>.tmp_stock_move.send_time, Column: edw.fct_stock_move.send_time)
(Column: <default>.tmp_stock_move.sku_sk, Column: edw.fct_stock_move.sku_sk)

**Comment by reata** [comment]
Yet another edge case, thanks for reporting.

Can you try current_timestamp(), that way, at least send_date can be parsed.

Also, we won't give you back current_timestamp() -> etl_time lineage because pure function is ignored for now.

**Comment by wonb168** [comment]
try current_timestamp()?
oh,no. in postgresql, current_timestamp() is not a function.
current_timestamp as etl_time, before as  if not a column, do not ignore, perserve it.

**Comment by reata** [comment]
> try current_timestamp()? oh,no. in postgresql, current_timestamp() is not a function. current_timestamp as etl_time, before as if not a column, do not ignore, perserve it.

I see. I just checked current_timestamp is reserved keyword in ANSI SQL 2016 standard.
https://en.wikipedia.org/wiki/SQL_reserved_words

I think we should find a way to support it.

**Comment by reata** [comment]
A simplified test case:
```sql
INSERT INTO tab1
SELECT current_timestamp as col1,
       col2,
       col3
FROM tab2
```
sqlparse cannot generate the AST correctly, which lead to all the columns after current_timestamp being ignored. So no column lineage with current v1.3.7.

After we release v1.4.0 next month, you shall be able to use --dialect=postgres in command line, or in python `LineageRunner(sql, dialect="postgres")` to leverage our new parser(sqlfluff) and get the correct result, which would be:
```
<default>.tab1.col2 <- <default>.tab2.col2
<default>.tab1.col3 <- <default>.tab2.col3
```
