### ISSUE TITLE
When the Target Table name is <SCHEMA>.<TABLE> And Query in Parenthesis it fails to determine lineage

### ISSUE THREAD

**Issue by snowmanwangyal** [reata/sqllineage#249]
When the target table name has a schema include, it fails:

`insert into public.event_location ( select event.eventid as eventid, event.eventname as eventname, event.venueid as venueid, venue.venuename as venuename, venue.venuecity as venuecity, venue.venuestate as venuestate from public.event inner join venue on venue.venueid = event.venueid )`

**Comment by reata** [comment]
Yes, this is a bug. Thanks for reporting.

As a walk-around, you can try remove the parenthesis first. We do have a lot of weird cases related to parenthesis.

**Comment by reata** [comment]
With v1.3.7, it will work only if:
1) target table is unqualified 
```sql
insert into event_location ( select event.eventid as eventid, event.eventname as eventname, event.venueid as venueid, venue.venuename as venuename, venue.venuecity as venuecity, venue.venuestate as venuestate from public.event inner join venue on venue.venueid = event.venueid )
```

OR

2) query is not surrounded by parenthesis
```sql
insert into public.event_location select event.eventid as eventid, event.eventname as eventname, event.venueid as venueid, venue.venuename as venuename, venue.venuecity as venuecity, venue.venuestate as venuestate from public.event inner join venue on venue.venueid = event.venueid
```
With both in the game, it breaks.


After we release v1.4.0 next month, you shall be able to use --dialect=ansi in command line, or in python LineageRunner(sql, dialect="ansi") to leverage our new parsing capability and get the correct result.
