### ISSUE TITLE
Exception when sql contain json_tuple

### ISSUE THREAD

**Issue by HuanjieGuo** [reata/sqllineage#264]
sqllineage.exceptions.SQLLineageException: An Identifier is expected, got IdentifierList[XXXX] instead.

**Comment by reata** [comment]
Can you give me an sample SQL to check?

**Comment by HuanjieGuo** [comment]
**Here is the sample**:
```
create or replace temporary view table_a_v
as
select
e,
f,
g,
h
from table_b_v
lateral view json_tuple(node_data_txt, 'e_name', 'f_name', 'g_name', 'h_name') b as e, f, g, h

```
**And you got:**
sqllineage.exceptions.SQLLineageException: An Identifier is expected, got IdentifierList[value: json_tuple(node_data_txt, 'e', 'f', 'g', 'h') b as e, f, g, h] instead.

**Comment by reata** [comment]
This is a duplication of #225, we possibly need to monkey patch sqlparse again. Please follow-up on that ticket.
