### ISSUE TITLE
insert overwrite cannot have DB name

### ISSUE THREAD

**Issue by HuanjieGuo** [reata/sqllineage#268]
**Without DB name : correct**
insert overwrite table c
(
 select * from a
 UNION
 select * from b
)

source: [Table: <default>.a, Table: <default>.b]
target: [Table: <default>.c]

**With DB name : wrong**
insert overwrite table db.c
(
 select * from a
 UNION
 select * from b
)
    
source: []
target: [Table: db.c]

**Comment by reata** [comment]
This is a duplication of #218 , please refer to the details there.
