### ISSUE TITLE
sqllineage.exceptions.SQLLineageException: An Identifier is expected, got Function

### ISSUE THREAD

**Issue by erkrvishal** [reata/sqllineage#272]
I tried running the sqllineage on my SQL query mentioned below:
(Part of code I have mentioning below)

******************
     select
        DATE_FORMAT(u.hour,'%Y-%m-%d %H:00:00') as hour
        from  unnest(sequence(cast(insert_from_timestamp as timestamp), cast(insert_to_timestamp as timestamp), interval '1' hour))
******************
Error got:

sqllineage.exceptions.SQLLineageException: An Identifier is expected, got Function[value: unnest(sequence(cast(insert_from_timestamp as timestamp), cast(insert_to_timestamp as timestamp), interval '1' hour))] instead.

**Comment by dvasdekis** [comment]
I get the same error when running code like the below (in MS Synapse Ondemand T-SQL):
```sql
WITH name_values as (
    SELECT 'LASTNAME' as Last_Name, 'FIRSTNAME SECONDNAME' as First_and_Middle_Names UNION ALL
    SELECT 'LASTNAMETWO' as Last_Name, 'Goodfirstname' as First_and_Middle_Names UNION ALL
    SELECT 'Goodlastname' as Last_Name, 'FIRST SECOND' as First_and_Middle_Names
)
SELECT 
Last_Name
, First_and_Middle_Names
-- Below subselect applies Titlecase to the first letter of each word
-- T-SQL has no 'proper' function (unlike INITCAP() in Postgres) so had to create this solution
, (SELECT STRING_AGG(UPPER(LEFT(value, 1)) + LOWER(RIGHT(value, LEN(value)-1)) , ' ') FROM STRING_SPLIT (TRIM(Last_Name), ' ')) AS nice_lastname
, (SELECT STRING_AGG(UPPER(LEFT(value, 1)) + LOWER(RIGHT(value, LEN(value)-1)) , ' ') FROM STRING_SPLIT (TRIM(First_and_Middle_Names), ' ')) AS nice_firstnames
FROM name_values ;
```
I think a stored procedure would work around it, but I'll create a test case and see what I can puzzle out as this structure is used semi-frequently.

**Comment by reata** [comment]
What's the output for `STRING_SPLIT (TRIM(Last_Name), ' '))`?

As the message suggests, after keyword FROM, we expect a table name (identifier), not a function. Once we detect a function, a exception is thrown.
