### ISSUE TITLE
Add details to column lineages

### ISSUE THREAD

**Issue by IterableTrucks** [reata/sqllineage#294]
#281 
In some senarios, we need to inspect the deriving expressions from multiple source columns to a target column. For example, considering the following statement:
```SQL
INSERT INTO t1(col1, col2) select a as col1, b+c as col2 from t2;
```
, in the current column lineage result there's no information on how t2.b and t2.c derive t1.col2. To make the lineage more detailed, I add an expression field to sqllineage.core.models.Column. With new Column, you can inspect the expression in this way:
```Python
>>> result=LineageRunner("INSERT INTO t1(col1, col2) select a as col1, b+c as col2 from t2;")
>>> result.get_column_lineage()[2][1].expression
ColumnExpression(is_identity=False, token=<Operation 'b+c' at 0x7F39A21FD9A0>)
```

**Comment by reata** [comment]
Yeah, this makes sense to preserve the raw data. Let's work on it.
