### ISSUE TITLE
non alias tables parser is unknown table's name

### ISSUE THREAD

**Issue by wang3680** [reata/sqllineage#304]
sql:
    SELECT  CASE WHEN branch_no = '100' THEN '1' 
                 WHEN branch_no = '200' THEN '2' 
                 WHEN branch_no = '300' THEN '3' 
                 ELSE branch_no END AS branch_no
           ,COUNT(DISTINCT client_id) AS client_hj_collect --呼叫采集客户数
    FROM ods10.`ods_hjzx_hs_cc_act_part_member` a
    LEFT JOIN ods00.ods_uf20_tdhcj_tdhsysarg sj
    ON 1=1 
    WHERE a.biz_type = 'CLHF_YJY_2020'
    AND a.act_id = '386'
    GROUP BY  branch_no
results:
![image](https://user-images.githubusercontent.com/5953877/196108098-3eb99ca2-5349-4f67-83ea-932fb3b214cd.png)
sql is not reguar, columns is non alias , result have not parse table's name, is unknown

**Comment by reata** [comment]
There's no way for sqllineage to tell whether client_id/branch_no comes from ods10.ods_hjzx_hs_cc_act_part_member or ods00.ods_uf20_tdhcj_tdhsysarg without specifying the table prefix. You can fix it by adding the alias prefix like a.client_id or sj.client_id.

This is one of the drawback for not integrating with metadata. It's expected behaviour.

**Comment by wang3680** [comment]
Thanks.I can get metadata. so I could find those columns from metadata if tables are unknown

**Comment by wang3680** [comment]
But if it has many unknown tables ,how can I get tables from metadata?
![image](https://user-images.githubusercontent.com/5953877/196191434-a235d01b-f370-4563-bb32-bd44db4d652a.png)
If sqllineage could get T2 or T3 's subsql?

**Comment by reata** [comment]
Can you provide the full SQL as text so I can better understand your question?

**Comment by wang3680** [comment]
SET hive.exec.dynamic.partition = true;
SET mapred.reduce.tasks = 3;
INSERT OVERWRITE TABLE ods10.test PARTITION (data_year)
SELECT branch.branch_no as branch_no
       ,branch.branch_name AS branch_name
       ,sum(T1.client_all)          
	   ,sum(T2.client_hj_collect) 
	   ,substr(sum(T2.client_hj_collect)/sum(T1.client_all),1,6)*100 
	   ,sum(T3.client_hj_visit)
	   ,substr(sum(T3.client_hj_visit)/sum(T2.client_hj_collect),1,6)*100 
       ,'2021' AS  data_year
FROM 
(
     SELECT  aa.branch_no 
            ,COUNT(DISTINCT aa.client_id) AS client_all 
    FROM ods01.ods_uf20_hs_asset_client_all aa
    WHERE aa.data_date =  '20201231'                      	
    and aa.client_status = '0'
    AND aa.`open_date` <='20201231'               
    AND aa.`branch_no` NOT IN ('8888','810','601')
    GROUP BY  aa.branch_no
)T1
LEFT JOIN 
(
    SELECT  CASE WHEN branch_no = '100' THEN '1' 
                 WHEN branch_no = '200' THEN '2' 
                 WHEN branch_no = '300' THEN '3' 
                 ELSE branch_no END AS branch_no
           ,COUNT(DISTINCT client_id) AS client_hj_collect 
    FROM ods10.`ods_hjzx_hs_cc_act_part_member` a
    LEFT JOIN ods00.ods_uf20_tdhcj_tdhsysarg sj
    ON 1=1 
    WHERE a.biz_type = 'CLHF_YJY_2020'
    AND a.act_id = '386'
    GROUP BY  branch_no
)T2
ON T1.branch_no=T2.branch_no
LEFT JOIN 
(
    SELECT  CASE WHEN branch_no = '100' THEN '1' 
                 WHEN branch_no = '200' THEN '2' 
                 WHEN branch_no = '300' THEN '3' 
                 ELSE branch_no END AS branch_no
           ,COUNT(DISTINCT client_id) AS client_hj_visit  
    FROM ods10.ods_hjzx_hs_cc_hf_report b
    LEFT JOIN ods00.ods_uf20_tdhcj_tdhsysarg sj
    ON 1=1 
    WHERE b.type='CL' and b.act_id = '386'
    GROUP BY  branch_no
)T3
ON T1.branch_no=T3.branch_no
LEFT JOIN
(            SELECT aa.branch_no
                 ,aa.new_branch_no
                 ,bb.branch_name 
            FROM dic.dic_uf20_brancharea aa 
            LEFT JOIN dic.dic_uf20_brancharea bb
            ON aa.new_branch_no = bb.branch_no
) branch
ON branch.branch_no = T1.branch_no
LEFT JOIN ods00.ods_uf20_tdhcj_tdhsysarg sj
ON 1=1
GROUP BY branch.branch_no,branch.branch_name,sj.pre_init_date

**Comment by reata** [comment]
Everything is expected behavior here. Let me explain for subquery T2:

```sql
(
SELECT CASE WHEN branch_no = '100' THEN '1'
WHEN branch_no = '200' THEN '2'
WHEN branch_no = '300' THEN '3'
ELSE branch_no END AS branch_no
,COUNT(DISTINCT client_id) AS client_hj_collect
FROM ods10.ods_hjzx_hs_cc_act_part_member a
LEFT JOIN ods00.ods_uf20_tdhcj_tdhsysarg sj
ON 1=1
WHERE a.biz_type = 'CLHF_YJY_2020'
AND a.act_id = '386'
GROUP BY branch_no
)T2
```

By only look at the SQL as text, I know subquery T2 will have two columns: branch_no and client_hj_collect.
T2.branch_no is using a case when clause, sourcing a column also called branch_no. But I don't know whether branch_no is from ods10.ods_hjzx_hs_cc_act_part_member or ods00.ods_uf20_tdhcj_tdhsysarg. Both could be true without metadata info.

Yes, you know the answer. But sqllineage doesn't support user providing metadata yet. The best you can do, is to rewrite it as the following:
```sql
LEFT JOIN
(
SELECT CASE WHEN sj.branch_no = '100' THEN '1'
WHEN sj.branch_no = '200' THEN '2'
WHEN sj.branch_no = '300' THEN '3'
ELSE sj.branch_no END AS branch_no
,COUNT(DISTINCT a.client_id) AS client_hj_collect
FROM ods10.ods_hjzx_hs_cc_act_part_member a
LEFT JOIN ods00.ods_uf20_tdhcj_tdhsysarg sj
ON 1=1
WHERE a.biz_type = 'CLHF_YJY_2020'
AND a.act_id = '386'
GROUP BY branch_no
)T2
ON T1.branch_no=T2.branch_no
```

**Comment by wang3680** [comment]
thanks
