### ISSUE TITLE
[Enhancement] Use curved lines instead of straight lines in the graphs

### ISSUE THREAD

**Issue by turekv** [reata/sqllineage#320]
Would it please be possible to use curved lines (e.g., Bézier curves) as connectors instead of straight lines? In my opinion this would significantly improve the "readability" of the graphs as well as aesthetics.

The lines could perhaps always connect perpendicularly to the respective terminal elements.

**Comment by reata** [comment]
I like this idea! Any chance you might be interested for a PR?

**Comment by reata** [comment]
We're so much in need of frontend expertise.

I'll try this later to see if it's a easy config change.

**Comment by reata** [comment]
In light of https://github.com/cytoscape/cytoscape.js/issues/2579, here's the preview:

Table Level:
![tpcds_query02_table](https://user-images.githubusercontent.com/8022906/209116715-ed78a11e-567c-4ee0-9cc4-f75b50be16bb.jpg)

Column Level:
![tpcds_query02_column](https://user-images.githubusercontent.com/8022906/209116674-a723d759-537d-4fd0-8c93-ba5154f4119d.jpg)
