### ISSUE TITLE
Source tables not found for views with both column list and select in parenthesis

### ISSUE THREAD

**Issue by fredriv** [reata/sqllineage#322]
When ingesting Snowflake tables and views into Open Metadata, I noticed that it was unable to find the lineage for views.

It seems `sqllineage` does not find the source table when the view query has both an explicit column list as well as the select expression inside parenthesis. The tests below are run with latest `sqllineage` v1.3.7.

Failing example - expected `b.baz` in source tables:
```
sqllineage -e "create view a.foo (bar) as (select bar from b.baz)"
Statements(#): 1
Source Tables:

Target Tables:
    a.foo
```

The lineage is correct if either the view column list is dropped or if the select expression is not in parenthesis:

```
sqllineage -e "create view a.foo as (select bar from b.baz)"
Statements(#): 1
Source Tables:
    b.baz
Target Tables:
    a.foo
```

```
sqllineage -e "create view a.foo (bar) as select bar from b.baz"
Statements(#): 1
Source Tables:
    b.baz
Target Tables:
    a.foo
```

**Comment by fredriv** [comment]
Related to https://github.com/reata/sqllineage/issues/244 ?

**Comment by reata** [comment]
Sorry for the late reply, was on vacation recently.

This is the same as #212 , we don't support specifying column name/type in DDL yet. I'll close this one for duplication, please refer to the other issue for future progress.
