### ISSUE TITLE
coalesce function not count in column lineage using non-validating dialect

### ISSUE THREAD

**Issue by DragonLong90** [reata/sqllineage#325]
eg 1:  
```
create table etl_db.test_parse_column as
     select
            a.etl_source_db,
            substr( a.etl_job_name, 1, 2 ) as substr_test,
            coalesce ( a.etl_job_name, a.etl_source_table ) as coalesce_text
     from
         etl_db.table_dependency_column a
```

```
  │  ~/Downloads  sqllineage -f test.sql -l column                                                                      ✔ │ 22s  │ 15:21:11 
etl_db.test_parse_column.etl_source_db <- etl_db.table_dependency_column.etl_source_db
etl_db.test_parse_column.substr <- etl_db.table_dependency_column.substr
```

eg 2:
```
  create table etl_db.test_parse_column as
   select
            substr( a.etl_job_name, 1, 2 ) as substr_test,
            coalesce ( a.etl_job_name, a.etl_source_table ) as coalesce_text,
            a.etl_source_db
    from
        etl_db.table_dependency_column a
```
```
  │  ~/Downloads  sqllineage -f test.sql -l column                                                                   ✔ │ 1m 51s  │ 15:23:54 
etl_db.test_parse_column.substr <- etl_db.table_dependency_column.substr
```

**Comment by reata** [comment]
I can confirm that we do not parse coalesce for the moment. I'll try add that in future release.

But for substr, I think it should work fine. Which version are you using? With sqllineage v1.3.7, the substr lineage can be parsed correctly:

```bash
➜  sqllineage -f test1.sql -l column 
etl_db.test_parse_column.etl_source_db <- etl_db.table_dependency_column.etl_source_db
etl_db.test_parse_column.substr_test <- etl_db.table_dependency_column.etl_job_name
➜  sqllineage -f test2.sql -l column
etl_db.test_parse_column.substr_test <- etl_db.table_dependency_column.etl_job_name
```

**Comment by DragonLong90** [comment]
> I can confirm that we do not parse coalesce for the moment. I'll try add that in future release.
> 
> But for substr, I think it should work fine. Which version are you using? With sqllineage v1.3.7, the substr lineage can be parsed correctly:
> 
> ```shell
> ➜  sqllineage -f test1.sql -l column 
> etl_db.test_parse_column.etl_source_db <- etl_db.table_dependency_column.etl_source_db
> etl_db.test_parse_column.substr_test <- etl_db.table_dependency_column.etl_job_name
> ➜  sqllineage -f test2.sql -l column
> etl_db.test_parse_column.substr_test <- etl_db.table_dependency_column.etl_job_name
> ```

sqllineage is v1.3.7，substr is not correctly。In the hive syntax, nvl function  cannot be parsed correctly
```
 │  ~/Downloads  pip3 list                                                                                             ✔ │ 13s  │ 09:42:23 
Package           Version
----------------- -------
altgraph          0.17.2
astroid           2.12.13
cffi              1.15.1
cryptography      38.0.4
dill              0.3.6
future            0.18.2
isort             5.11.4
lazy-object-proxy 1.9.0
macholib          1.15.2
mccabe            0.7.0
networkx          2.8.8
pip               21.2.4
platformdirs      2.6.2
pycparser         2.21
pylint            2.15.9
PyMySQL           1.0.2
setuptools        58.0.4
six               1.15.0
sqllineage        1.3.7
sqlparse          0.4.3
tomli             2.0.1
tomlkit           0.11.6
typing_extensions 4.4.0
wheel             0.37.0
wrapt             1.14.1
WARNING: You are using pip version 21.2.4; however, version 22.3.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
  │  ~/Downloads  cat test.sql                                                                                                  ✔ │ 09:43:37 
create table etl_db.test_parse_column as
     select
            substr( a.etl_job_name, 1, 2 ) as substr_test
     from
         etl_db.table_dependency_column a
  │  ~/Downloads  sqllineage -f test.sql -l column                                                                              ✔ │ 09:43:43 
etl_db.test_parse_column.substr <- etl_db.table_dependency_column.substr
```

```
 │  ~/Downloads  cat test.sql                                                                                          ✔ │ 20s  │ 09:51:54 
create table etl_db.test_parse_column as
     select
            nvl( a.etl_job_name, 1 ) as substr_test
     from
         etl_db.table_dependency_column a
  │  ~/Downloads  sqllineage -f test.sql -l column                                                                              ✔ │ 09:52:02 
```

**Comment by reata** [comment]
I see, sqlparse has change of behavior between 0.4.1 and 0.4.3, with sqllineage=1.3.7 and sqlparse=0.4.1, it will work fine.

Please try pin your sqlparse to 0.4.1 to solve the substr issue temporarily. We're working on a long term solution by replacing sqlparse with another parser.

**Comment by DragonLong90** [comment]
> nvl( a.etl_job_name, 1 ) as substr_test



> I see, sqlparse has change of behavior between 0.4.1 and 0.4.3, with sqllineage=1.3.7 and sqlparse=0.4.1, it will work fine.
> 
> Please try pin your sqlparse to 0.4.1 to solve the substr issue temporarily. We're working on a long term solution by replacing sqlparse with another parser.

Thank you very much. sqlparse version 0.4.1 solves the problem of nvl and substr function parsing

**Comment by reata** [comment]
with v1.4.x release, you should be able to get the correct result using ansi dialect. 

But the default non-validating dialect still suffers from the exact issue reported here, we should fix this.

**Comment by reata** [comment]
coalesce is defined as keyword in sqlparse. The lack of capability to handle reserved keyword and non-reserved keyword is the major reason we're deprecating sqlparse and move to sqlfluff. Thus this will not be supported with non-validating dialect.

**Comment by reata** [comment]
Also the problem is not with coalesce, rather coalesce + whitespace. Removing the whitespace between coalesce and parenthesis will make non-validate dialect work. Again, we won't fix this.
