### ISSUE TITLE
Column lineage does not work for CAST to Parameterized Data Type

### ISSUE THREAD

**Issue by azurewtl** [reata/sqllineage#329]
I guess the issus is that "Type(*)" is recognized as a subquery, instead of a type in "CAST(col AS Type(*))"

Input SQL:
```
INSERT
     OVERWRITE tbl_dst(col1, col2)
SELECT
     CAST(name AS VARCHAR) AS col1,
     CAST(age AS VARCHAR(35)) AS col2,
FROM
     tbl_src
```

Expected Output:
```
<default>.tbl_dst.col1 <- name
<default>.tbl_dst.col2 <- age
```

Current Output:
`<default>.tbl_dst.col1 <- name`

**Comment by reata** [comment]
You're right. We don't support parameterized data type yet. Also `decimal(18, 0)` doesn't work while `decimal` works. It's the same reason behind.

This is a bug we should fix.

**Comment by reata** [comment]
Please upgrade to v1.4.x version and use sparksql/hive dialect. We won't support this in v1.3.x or v1.4.x non-validating dialect.
