### ISSUE TITLE
Bug Report: SELECT * not supported by sqlineage

### ISSUE THREAD

**Issue by ericzhou571** [reata/sqllineage#330]
Hi all, 

Description
When using SELECT * in a SQL query or inside the subquery of a SQL, sqlineage is unable to provide accurate results.

**Steps to Reproduce**
```
sql = """
insert into current_table
select a.*
from
  (select allData.*,
          sncode+creationtime as ranktime
   from allData) a
where a.ranktime = 1
"""
k = LineageRunner(sql)
k._eval()
print(k.get_column_lineage(False))
```
**Expected Results**

> [(Column: <default>.alldata.*, Column: a.*, Column: <default>.current_table.*),
>  (Column: Column: a.ranktime, Column: <default>.current_table.ranktime),
>  (Column: <default>.alldata.creationtime, Column: a.ranktime),
>  (Column: <default>.alldata.sncode, Column: a.ranktime)]

**Actual Results**

> [(Column: <default>.alldata.*, Column: a.*, Column: <default>.current_table.*),
>  (Column: <default>.alldata.creationtime, Column: a.ranktime),
>  (Column: <default>.alldata.sncode, Column: a.ranktime)]

**Comment by reata** [comment]
Yes, we have some issues in dealing with `*` as a special column. Will fix it in future release.

**Comment by reata** [comment]
I can not reproduce your results.

I tried v1.3.8 and v1.4.2 version, both of them output below as column lineage:
```
<default>.current_table.* <- a.* <- <default>.alldata.*
```

Can you share the version you're using?

**Comment by reata** [comment]
Close as no further response.
