### ISSUE TITLE
Missing column lineage from SELECT DISTINCT using non-validating dialect

### ISSUE THREAD

**Issue by duongphannamhung** [reata/sqllineage#356]
Hi, 

I've tested to confirm two versions on an venv of `python 3.9.6`:
- the old one with: `sqllineage-1.3.7`
- the newest one: `sqllineage-1.4.1`

My SQL and code:
```
SQL = 
"""
WITH tb_dataraw_distinct AS 
(
  SELECT DISTINCT DATE(created_at,'Asia/Bangkok') AS created_date_key
        ,order_id
        ,city_id 
        ,deliveries_count
        ,category
        ,total_cod
        ,CASE WHEN total_cod > 0 THEN 1 ELSE 0 END AS is_cod
        ,last_order_status
        ,cancellation_reasons
  FROM `bi_dim_fact.tb_delivering_order_process`
 WHERE partition_date >= DATE_SUB(CURRENT_DATE('+7:00'), INTERVAL 7 DAY)
),
tb_source AS
(
  SELECT created_date_key
        ,city_id
        ,is_cod
        ,deliveries_count
        ,category
        ,last_order_status AS last_order_status_id 
        ,CASE WHEN last_order_status = 1 THEN  'cancel_by_sender_af_accepted_by_driver' 
              WHEN last_order_status = 2 THEN  'delivered'
              WHEN last_order_status = 5 THEN  'returned'
              WHEN last_order_status = 7 THEN  'cancel_by_driver'
              WHEN last_order_status = 24 THEN 'cancel_by_sender_bf_accepted_by_driver'
              WHEN last_order_status = 25 THEN 'not_find_driver'
              WHEN last_order_status = 26 THEN 'cancel_by_admin'
              WHEN last_order_status = 27 THEN 'complete_b_admin'END last_order_status            
        ,cancellation_reasons      
        ,COUNT(order_id) AS cancelled_requests
    FROM tb_dataraw_distinct AS od
  GROUP BY 1,2,3,4,5,6,7,8  
)
,
tb_history AS 
(
   SELECT *
     FROM `bi_dashboard.tb_bedelivery_cancelled_reasons` 
    WHERE created_date_key < DATE_SUB(CURRENT_DATE('+7:00'), INTERVAL 7 DAY)  
)
SELECT * FROM tb_source
UNION ALL
SELECT * FROM tb_history
"""
```
```
from sqllineage.runner import LineageRunner
print(LineageRunner(SQL).get_column_lineage(False))
```

**The output from the old version (1.3.7) is what I expected:**

[(Column: bi_dim_fact.tb_delivering_order_process.total_cod, Column: tb_dataraw_distinct.total_cod), (Column: bi_dashboard.tb_bedelivery_cancelled_reasons.*, Column: tb_history.*), (Column: bi_dim_fact.tb_delivering_order_process.cancellation_reasons, Column: tb_dataraw_distinct.cancellation_reasons, Column: tb_source.cancellation_reasons), (Column: bi_dim_fact.tb_delivering_order_process.order_id, Column: tb_dataraw_distinct.order_id, Column: tb_source.cancelled_requests), (Column: bi_dim_fact.tb_delivering_order_process.category, Column: tb_dataraw_distinct.category, Column: tb_source.category), (Column: bi_dim_fact.tb_delivering_order_process.city_id, Column: tb_dataraw_distinct.city_id, Column: tb_source.city_id), (Column: bi_dim_fact.tb_delivering_order_process.created_at, Column: tb_dataraw_distinct.created_date_key, Column: tb_source.created_date_key), (Column: bi_dim_fact.tb_delivering_order_process.deliveries_count, Column: tb_dataraw_distinct.deliveries_count, Column: tb_source.deliveries_count), (Column: bi_dim_fact.tb_delivering_order_process.total_cod, Column: tb_dataraw_distinct.is_cod, Column: tb_source.is_cod), (Column: bi_dim_fact.tb_delivering_order_process.last_order_status, Column: tb_dataraw_distinct.last_order_status, Column: tb_source.last_order_status), (Column: bi_dim_fact.tb_delivering_order_process.last_order_status, Column: tb_dataraw_distinct.last_order_status, Column: tb_source.last_order_status_id)]

**And on the newest version there're some missing these `bi_dim_fact` dataset:**

[(Column: bi_dashboard.tb_bedelivery_cancelled_reasons.*, Column: tb_history.*), (Column: tb_dataraw_distinct.cancellation_reasons, Column: tb_source.cancellation_reasons), (Column: tb_dataraw_distinct.order_id, Column: tb_source.cancelled_requests), (Column: tb_dataraw_distinct.category, Column: tb_source.category), (Column: tb_dataraw_distinct.city_id, Column: tb_source.city_id), (Column: tb_dataraw_distinct.created_date_key, Column: tb_source.created_date_key), (Column: tb_dataraw_distinct.deliveries_count, Column: tb_source.deliveries_count), (Column: tb_dataraw_distinct.is_cod, Column: tb_source.is_cod), (Column: tb_dataraw_distinct.last_order_status, Column: tb_source.last_order_status), (Column: tb_dataraw_distinct.last_order_status, Column: tb_source.last_order_status_id)]

**Comment by duongphannamhung** [comment]
I've already got the result I expected on the new sqllineage version when setting dialect=bigquery, which is the db engine I currently use. Thank you very much for your contribution.

**Comment by reata** [comment]
Thanks for reporting this. We did lose the capability to handle column lineage in `SELECT DISTINCT` using non-validating dialect. Although non-validating dialect is gone in the long term. We need to keep backward compatibility in v1.4.x. This is something we should fix.

a simplified test case:
```sql
INSERT INTO tgt
SELECT DISTINCT col FROM src;
```

v1.3.7 column lineage:
```
$ sqllineage -f test.sql -l column
<default>.tgt.col <- <default>.src.col
```

v1.4.1 column lineage using non-validating, nothing shows up:
```
$ sqllineage -f test.sql -l column --dialect=non-validating
```

v1.4.1 column lineage using bigquery (or any other dialect that's validating):
```
$ sqllineage -f test.sql -l column --dialect=bigquery
<default>.tgt.col <- <default>.src.col
```
