### ISSUE TITLE
Support declare statement in tsql dialect

### ISSUE THREAD

**Issue by SunMaungOo** [reata/sqllineage#357]
I have a valid tsql script which doesn't work with **tsql** dialect but work with **non-validating** dialect. 

```
from sqllineage.runner import LineageRunner

sql = """

DECLARE @age int = 10;

SELECT Name,@age 
FROM People;

"""

lineage = LineageRunner(sql,dialect="tsql")

print(lineage)

```

The error message shown is 

```
UnsupportedStatementException: SQLLineage doesn't support analyzing statement type [declare_segment] for SQL:DECLARE @age int = 10;
```

It look like the **DECLARE** statement is not supported.  Is there a reason why the **DECLARE** statement is not supported?

When I run the above code in **non-validating** , it work

```
from sqllineage.runner import LineageRunner

sql = """

DECLARE @age int = 10;

SELECT Name,@age 
FROM People;

"""

lineage = LineageRunner(sql,dialect = "non-validating")

print(lineage)

```

Output 

```
Statements(#): 2
Source Tables:
    <default>.people
Target Tables:
```

**Comment by reata** [comment]
One of the reasons we introduce dialect-awareness lineage is to better control what dialect-specific feature we support and what not.

non-validating is acting with best-effort strategy, it doesn't care about syntax validity. For your case, it's in your favor as non-validating just ignore the declare statement. We see in other cases (MERGE statement before v1.4.x as an example) when we haven't implemented analyzing logic and non-validating just gives confusing result, which is what we want to avoid.

Back to declare statement. We can choose to ignore it in tsql dialect as well. For table level lineage, it should act as expected. But column lineage is something we need to design:

a simplified SQL test case
```
DECLARE @age int = 10;

INSERT INTO tgt
SELECT Name,@age
FROM People;
```

Column Lineage Output Choice 1, this is what non-validating does right now. It treats `@age` as a column name:
```
<default>.tgt.@age <- <default>.people.@age
<default>.tgt.name <- <default>.people.name
```

Column Lineage Output Choice 2, when we understand `@age` is a variable and assigned to a constant value, thus treat it as `SELECT NAME, 10 FROM People`
```
<default>.tgt.name <- <default>.people.name
```

It's hard to make these choices actually. Is declare statement just variable assignment or is it like macro/template? More information is needed, and we should refer to tsql manual (https://learn.microsoft.com/en-us/sql/t-sql/language-elements/declare-local-variable-transact-sql?view=sql-server-ver16) before implementing this.

Hope this clarifies your question. For the time being, you can still rely on non-validating dialect. And we'll try officially support DECLARE statement.

**Comment by reata** [comment]
I took some time to read the Microsoft docs, and it looks to that DECLARE is mostly used to assign variable to a constant value. For constant value, the best way to do this is simply ignore the variable. For sql
```sql
DECLARE @age int = 10;

INSERT INTO tgt
SELECT Name,@age
FROM People;
```

The column lineage would be
```
<default>.tgt.name <- <default>.people.name
```

And the table lineage would be
```
Source Tables:
    <default>.people
Target Tables:
    <default>.tgt
```


Declare a variable to be of type table is special though. For the query in official docs:
```
DECLARE @MyTableVar TABLE (
    EmpID INT NOT NULL,
    OldVacationHours INT,
    NewVacationHours INT,
    ModifiedDate DATETIME);

UPDATE TOP (10) HumanResources.Employee
SET VacationHours = VacationHours * 1.25
OUTPUT INSERTED.BusinessEntityID,
       DELETED.VacationHours,
       INSERTED.VacationHours,
       INSERTED.ModifiedDate
INTO @MyTableVar;

--Display the result set of the table variable.
SELECT EmpID, OldVacationHours, NewVacationHours, ModifiedDate
FROM @MyTableVar;
```

Do you need `@MyTableVar` to be source table, or can we ignore it as well? @SunMaungOo
