### ISSUE TITLE
can function like avg max can list in result?

### ISSUE THREAD

**Issue by Tangsonghuai** [reata/sqllineage#359]
can function like avg max can list in result?

**Comment by reata** [comment]
I don't quite understand the request. Can you give the sample SQL as well as your expected output? Thanks.

**Comment by Tangsonghuai** [comment]
thinks for your answer,
such like this 
'''
insert into B(b)
select max(a)
from A
'''
i would to know this function 'max' can list in DAG's picture
emmm , like this   a -->max--> b or max(a) -->b

**Comment by Tangsonghuai** [comment]
> I don't quite understand the request. Can you give the sample SQL as well as your expected output? Thanks.

hello?Are you here?

**Comment by reata** [comment]
This is not supported yet. Please refer to #343 for future update.
