### ISSUE TITLE
sqlparse v0.4.4 breaks monkey patching: SQL_REGEX doesn't contain compiled regexes anymore

### ISSUE THREAD

**Issue by tamas7** [reata/sqllineage#361]
When importing the package, the `_patch_updating_lateral_view_lexeme()` function fails with the following error:
```
def _patch_updating_lateral_view_lexeme() -> None:
    for i, (regex, lexeme) in enumerate(SQL_REGEX):
        if regex("LATERAL VIEW EXPLODE(col)"):

E   TypeError: 'str' object is not callable
```

I think this is due to the latest 0.4.4 release of `sqlparse` where they introduced a change that changes `SQL_REGEX` to not have compiled regexes anymore: https://github.com/andialbrecht/sqlparse/pull/693/files#diff-1e8198a38c2584359246d41ebdcd5d0a7ca47be5dbe1a13ae33b2f9ef8452784L109

The regexes are now compiled in the `lexer.Lexer.set_SQL_REGEX()` method, but the result of that doesn't looks like it is exposed as a public interface. Could then make sense to have `sqllineage` compile these instead, if necessary.

**Comment by reata** [comment]
Thanks for dig into this. It's very helpful to have these insights.

We have a PR (#360) to pin sqlparse to v0.4.3 in short term. Feel free to contribute if you have any idea. 

sqlparse is making the lexer configurable, I guess we can now configure it. Worst scenario, we patch certain part of the Lexer class. That's my two cents. As we were doing monkey patching already, we are not honoring the public interface anyway.

**Comment by tamas7** [comment]
Hi thanks for the update! Was looking to create a PR with a more long term fix, but discovered that the `is_keyword()` function was also moved out from `sqlparse/keywords.py` and made it into the `Lexer` class as an instance method.

The `is_keyword()` function seems to be used in `/Users/tamas.adorjani/GitHub/sqllineage/sqllineage/core/parser/sqlparse/models.py`.

Trying to switch to use the new method that is now part of the `Lexer` class is producing quite a bit of unit test failures, which I think would need a bit more effort from my side to figure out why, as I'm quite new to this codebase.

If you have any advice or pointers for me, that would be greatly appreciated.

**Comment by reata** [comment]
Just refer to #360 to see the change we made.
