### ISSUE TITLE
HOW CAN I SEE THE Lineage Visualization？

### ISSUE THREAD

**Issue by emmeem** [reata/sqllineage#362]
when i input sqllineage -g -f test1.sql ，the terminal is output SQLLineage Running on http://localhost:5000..... ,but nothing show, please tell me how can i see  the Lineage Visualization？thanks

**Comment by jianJizz** [comment]
Just replace localhost with 127.0.0.1

**Comment by emmeem** [comment]
您好，您的邮件我已收到，我会尽快回复您。
