### ISSUE TITLE
Support postgres style type casts "keyword::TIMESTAMP"

### ISSUE THREAD

**Issue by longjieCh** [reata/sqllineage#364]
Hi, thanks for your work, 

I got a `NoneType error` when use sql keywords within type as `keyword::TIMESTAMP`
such as:
```
sql1 = "select day from A " #no error
sql2 = "select day1::TIMESTAMP from A " #no error

sql3 = "select day::TIMESTAMP from A " #error
sql4 = "select clob::TIMESTAMP from A " #error
sql5 = "select class::TIMESTAMP from A " #error
```

if i use [keywords in sql](http://www.postgres.cn/docs/9.4/sql-keywords-appendix.html), it will cause a `NoneType error`:

`AttributeError: 'NoneType' object has no attribute 'strip'`

**Comment by longjieCh** [comment]
NoneType error when use sql keywords within type as "keyword::TIMESTAMP"
such as:
sql1 = "select day from A " #no error
sql2 = "select day1::TIMESTAMP from A " #no error

sql3 = "select day::TIMESTAMP from A " #error
sql4 = "select clob::TIMESTAMP from A " #error
sql5 = "select class::TIMESTAMP from A " #error

if i use [keywords in sql](http://www.postgres.cn/docs/9.4/sql-keywords-appendix.html), it will cause a NoneType error:


`
C:\ProgramData\Anaconda3\lib\site-packages\sqllineage\runner.py in wrapper(*args, **kwargs)
     20         self = args[0]
     21         if not self._evaluated:
---> 22             self._eval()
     23         return func(*args, **kwargs)
     24 

C:\ProgramData\Anaconda3\lib\site-packages\sqllineage\runner.py in _eval(self)
    177             if s.token_first(skip_cm=True)
    178         ]
--> 179         self._stmt_holders = [LineageAnalyzer().analyze(stmt) for stmt in self._stmt]
    180         self._sql_holder = SQLLineageHolder.of(*self._stmt_holders)
    181         self._evaluated = True

C:\ProgramData\Anaconda3\lib\site-packages\sqllineage\runner.py in <listcomp>(.0)
    177             if s.token_first(skip_cm=True)
    178         ]
--> 179         self._stmt_holders = [LineageAnalyzer().analyze(stmt) for stmt in self._stmt]
    180         self._sql_holder = SQLLineageHolder.of(*self._stmt_holders)
    181         self._evaluated = True

C:\ProgramData\Anaconda3\lib\site-packages\sqllineage\core\analyzer.py in analyze(self, stmt)
     58             # DML parsing logic also applies to CREATE DDL
     59             holder = StatementLineageHolder.of(
---> 60                 self._extract_from_dml(stmt, AnalyzerContext())
     61             )
     62         return holder

C:\ProgramData\Anaconda3\lib\site-packages\sqllineage\core\analyzer.py in _extract_from_dml(cls, token, context)
    133             for next_handler in next_handlers:
    134                 if next_handler.indicator:
--> 135                     next_handler.handle(sub_token, holder)
    136         else:
    137             # call end of query hook here as loop is over

C:\ProgramData\Anaconda3\lib\site-packages\sqllineage\core\handlers\base.py in handle(self, token, holder)
     37         """
     38         if self.indicator:
---> 39             self._handle(token, holder)
     40             self.indicator = False
     41 

C:\ProgramData\Anaconda3\lib\site-packages\sqllineage\core\handlers\source.py in _handle(self, token, holder)
     56     def _handle(self, token: Token, holder: SubQueryLineageHolder) -> None:
     57         if self.column_flag:
---> 58             self._handle_column(token)
     59         else:
     60             self._handle_table(token, holder)

C:\ProgramData\Anaconda3\lib\site-packages\sqllineage\core\handlers\source.py in _handle_column(self, token)
    103             column_tokens = []
    104         for token in column_tokens:
--> 105             self.columns.append(Column.of(token))
    106 
    107     def end_of_query_cleanup(self, holder: SubQueryLineageHolder) -> None:

C:\ProgramData\Anaconda3\lib\site-packages\sqllineage\core\models.py in of(token)
    231                     token.get_real_name(),
    232                     source_columns=((token.get_real_name(), token.get_parent_name()),),
--> 233                     expression=ColumnExpression(True, None),
    234                 )
    235         else:

C:\ProgramData\Anaconda3\lib\site-packages\sqllineage\core\models.py in __init__(self, name, **kwargs)
    172         """
    173         self._parent: Set[Union[Table, SubQuery]] = set()
--> 174         self.raw_name = escape_identifier_name(name)
    175         self.source_columns = kwargs.pop("source_columns", ((self.raw_name, None),))
    176         self.expression = kwargs.pop("expression", ColumnExpression(True, None))

C:\ProgramData\Anaconda3\lib\site-packages\sqllineage\utils\helpers.py in escape_identifier_name(name)
      6 
      7 def escape_identifier_name(name: str):
----> 8     return name.strip("`").strip('"').strip("'")
      9 
     10 

AttributeError: 'NoneType' object has no attribute 'strip'
`

**Comment by reata** [comment]
After we release the v1.4.3, you shall be able to use postgres dialect to get the correct lineage for each query:

```shell
$ sqllineage -e "insert into foo select day from A" -l column --dialect=postgres            
<default>.foo.day <- <default>.a.day
$ sqllineage -e "insert into foo select day1::TIMESTAMP from A" -l column --dialect=postgres
<default>.foo.day1 <- <default>.a.day1
$ sqllineage -e "insert into foo select day::TIMESTAMP from A" -l column --dialect=postgres
<default>.foo.day <- <default>.a.day
$ sqllineage -e "insert into foo select clob::TIMESTAMP from A" -l column --dialect=postgres 
<default>.foo.clob <- <default>.a.clob
$ sqllineage -e "insert into foo select class::TIMESTAMP from A" -l column --dialect=postgres
<default>.foo.class <- <default>.a.class
```

Let me know if you're not using PostgreSQL though.
