### ISSUE TITLE
i find a problem that this can't support with temp table

### ISSUE THREAD

**Issue by Tangsonghuai** [reata/sqllineage#368]
`with as 
(
select id from k
) table12
insert into db3.table3 
select table12.id  from db1.table11
 join table12`
 like this ,
 with table can't parse by sqllineage
 
 it output 
 `db3.table3.id <- <default>.table12.id`

**Comment by Tangsonghuai** [comment]
i am sorry ,it support,please stop

**Comment by reata** [comment]
We have some regression issue with CTE in v1.4.x version. Please refer to #328 for update.
