### ISSUE TITLE
postgres merge into sql can not parse

### ISSUE THREAD

**Issue by chuxiangfeng** [reata/sqllineage#383]
`sqllineage -f temp2.sql -v --dialect=postgres`

temp2.sql is:
`MERGE INTO bbb t2\n            USING aaa t1 ON t1.row_key = t2.row_key\n            WHEN MATCHED  THEN\n            UPDATE SET ods_id=COALESCE(t1.ods_id, t2.ods_id),anc_source=COALESCE(t1.anc_source, t2.anc_source),anc_id=COALESCE(t1.anc_id, t2.anc_id),dy=COALESCE(t1.dy, t2.dy),up_update_time=COALESCE(t1.up_update_time, t2.up_update_time),up_create_time=COALESCE(t1.up_create_time, t2.up_create_time),change_code=3,update_time=localtimestamp\n            WHEN NOT MATCHED THEN\n            INSERT (ods_id,anc_source,anc_id,dy,up_update_time,up_create_time,change_code,create_time,update_time) \n            VALUES(t1.ods_id,t1.anc_source,t1.anc_id,t1.dy,t1.up_update_time,t1.up_create_time,1,localtimestamp,localtimestamp)\n   `     

result is:
```
Traceback (most recent call last):
  File "/Users/chuxiangfeng/PycharmProjects/pythonEffectiveS/venv/bin/sqllineage", line 8, in <module>
    sys.exit(main())
  File "/Users/chuxiangfeng/PycharmProjects/pythonEffectiveS/venv/lib/python3.9/site-packages/sqllineage/cli.py", line 101, in main
    runner.print_table_lineage()
  File "/Users/chuxiangfeng/PycharmProjects/pythonEffectiveS/venv/lib/python3.9/site-packages/sqllineage/runner.py", line 168, in print_table_lineage
    print(str(self))
  File "/Users/chuxiangfeng/PycharmProjects/pythonEffectiveS/venv/lib/python3.9/site-packages/sqllineage/runner.py", line 22, in wrapper
    self._eval()
  File "/Users/chuxiangfeng/PycharmProjects/pythonEffectiveS/venv/lib/python3.9/site-packages/sqllineage/runner.py", line 177, in _eval
    self._stmt_holders = [analyzer.analyze(stmt) for stmt in self._stmt]
  File "/Users/chuxiangfeng/PycharmProjects/pythonEffectiveS/venv/lib/python3.9/site-packages/sqllineage/runner.py", line 177, in <listcomp>
    self._stmt_holders = [analyzer.analyze(stmt) for stmt in self._stmt]
  File "/Users/chuxiangfeng/PycharmProjects/pythonEffectiveS/venv/lib/python3.9/site-packages/sqllineage/core/parser/sqlfluff/analyzer.py", line 44, in analyze
    raise InvalidSyntaxException(
sqllineage.exceptions.InvalidSyntaxException: This SQL statement is unparsable, please check potential syntax error for SQL:MERGE INTO bbb t2\n            USING aaa t1 ON t1.row_key = t2.row_key\n            WHEN MATCHED  THEN\n            UPDATE SET ods_id=COALESCE(t1.ods_id, t2.ods_id),anc_source=COALESCE(t1.anc_source, t2.anc_source),anc_id=COALESCE(t1.anc_id, t2.anc_id),dy=COALESCE(t1.dy, t2.dy),up_update_time=COALESCE(t1.up_update_time, t2.up_update_time),up_create_time=COALESCE(t1.up_create_time, t2.up_create_time),change_code=3,update_time=localtimestamp\n            WHEN NOT MATCHED THEN\n            INSERT (ods_id,anc_source,anc_id,dy,up_update_time,up_create_time,change_code,create_time,update_time) \n            VALUES(t1.ods_id,t1.anc_source,t1.anc_id,t1.dy,t1.up_update_time,t1.up_create_time,1,localtimestamp,localtimestamp)\n
```

**Comment by reata** [comment]
Is `\n` escaped or not? If it's two character `\` and `n` then surely it's invalid syntax. I tried the following sql string and it works fine

```
MERGE INTO bbb t2 USING aaa t1 ON t1.row_key = t2.row_key
    WHEN MATCHED THEN UPDATE SET ods_id = coalesce(t1.ods_id, t2.ods_id),
        anc_source = coalesce(t1.anc_source, t2.anc_source),
        anc_id = coalesce(t1.anc_id, t2.anc_id),
        dy = coalesce(t1.dy, t2.dy),
        up_update_time = coalesce(t1.up_update_time, t2.up_update_time),
        up_create_time = coalesce(t1.up_create_time, t2.up_create_time),
        change_code = 3,
        update_time = localtimestamp
    WHEN NOT MATCHED THEN INSERT (ods_id,
                                  anc_source,
                                  anc_id,
                                  dy,
                                  up_update_time,
                                  up_create_time,
                                  change_code,
                                  create_time,
                                  update_time)
        VALUES (t1.ods_id,
                t1.anc_source,
                t1.anc_id,
                t1.dy,
                t1.up_update_time,
                t1.up_create_time,
                1,
                localtimestamp,
                localtimestamp)

```

**Comment by chuxiangfeng** [comment]
> Is `\n` escaped or not? If it's two character `\` and `n` then surely it's invalid syntax. I tried the following sql string and it works fine
> 
> ```
> MERGE INTO bbb t2 USING aaa t1 ON t1.row_key = t2.row_key
>     WHEN MATCHED THEN UPDATE SET ods_id = coalesce(t1.ods_id, t2.ods_id),
>         anc_source = coalesce(t1.anc_source, t2.anc_source),
>         anc_id = coalesce(t1.anc_id, t2.anc_id),
>         dy = coalesce(t1.dy, t2.dy),
>         up_update_time = coalesce(t1.up_update_time, t2.up_update_time),
>         up_create_time = coalesce(t1.up_create_time, t2.up_create_time),
>         change_code = 3,
>         update_time = localtimestamp
>     WHEN NOT MATCHED THEN INSERT (ods_id,
>                                   anc_source,
>                                   anc_id,
>                                   dy,
>                                   up_update_time,
>                                   up_create_time,
>                                   change_code,
>                                   create_time,
>                                   update_time)
>         VALUES (t1.ods_id,
>                 t1.anc_source,
>                 t1.anc_id,
>                 t1.dy,
>                 t1.up_update_time,
>                 t1.up_create_time,
>                 1,
>                 localtimestamp,
>                 localtimestamp)
> ```

think you, is work fine
