### ISSUE TITLE
sqllineage.exceptions.SQLLineageException: An Identifier is expected, got Where[value: where ds = '${ds}'] instead

### ISSUE THREAD

**Issue by sh1shan** [reata/sqllineage#393]
sqllineage version 1.3.8
python version 3.7.2
sqllineage fails to parse the following query:
```sql
with day as (
select
    ,code
    ,name
    ,sum(qty) qty
    ,sum(amt) amt
    ,ds
from tmp.test_table_name1
where ds >= trunc('${ds}','YY')
group by
    ds
    ,code
    ,name
)
insert overwrite table tmp.test_table_name2 partition (ds)
select
    ,code
    ,name
    ,qty
    ,amt
    ,ds
from day
where ds = '${ds}'
```
error message is:
`sqllineage.exceptions.SQLLineageException: An Identifier is expected, got Where[value: where ds = '${ds}'] instead.`

**Comment by reata** [comment]
`day` is a keyword and we cannot handle non-reserved keyword used as table name very well in v1.3.x version. If you cannot upgrade to v1.4.x version, the only choice would be to manually remove this keyword before calling sqllineage:

```python
from sqlparse.keywords import KEYWORDS
KEYWORDS["DAY"]
```
