### ISSUE TITLE
problem on parsing name of identities contains "case" or "order" with some dialect

### ISSUE THREAD

**Issue by duongphannamhung** [reata/sqllineage#396]
with: `sqllineage==1.4.4`: `sqlparse=0.4.4` and `sqlfluff=2.0.3`
I have a sql and want to find column lineage

```sql
insert into target.order
select tab1.order , order.field_order
from be_dataset.tb_order as tab1
join be_dataset.order
```
(and also on replace "order" -> "case" in this sql)

On parsing with non-dialect, it works well. But try on some dialects like "ansi" / "bigquery" / "postgres" we got the `InvalidSyntaxException`. I just hot fix by replacing the identity string (like add prefix -> "order_xyz") when it was still the string sql (replace it when it writes into node) then it's fine. But I know this is the worst way to do it. Have you known this problem before, maybe you can give me the idea and I can help you with 👨🏻‍💻

**Comment by reata** [comment]
Order is a reserved keyword in most SQL dialects, which cannot be used as table/column name. I tried creating the table in postgresql and it does give me syntax error:
```sql
postgres=# create table order as select 1;
ERROR:  syntax error at or near "order"
LINE 1: create table order as select 1;
```

So I would say InvalidSyntaxException is the expected behavior and non-validating dialect actually got it wrong. That's also the major reason we introduce `sqlfluff` as `sqlparse` cannot tell reserved keywords based on dialect.

What is the dialect you're using? If order is allowed as table name, we can come to fix that.

**Comment by duongphannamhung** [comment]
I use most of the time with sqllineage solution for BigQuery. And in BQ we can create the dataset, table also column with the name "order". 
I just have a quick demonstration: image below

Actually, BQ need the small "\`" to recognize the name of these identifiers. So we can't query without use "\`" for this edge case. (the normal case we don't need \`)
<img width="1077" alt="image" src="https://github.com/reata/sqllineage/assets/77838344/7dd97389-fcf1-41ee-97d1-2ea4dd107563">

**Comment by reata** [comment]
I tried escape table name with backtick, and it seems we can output the correct result:

```sql
insert into target.`order`
select tab1.`order` , `order`.field_order
from be_dataset.tb_order as tab1
join be_dataset.`order`
```

```shell
sqllineage -f test.sql --dialect=bigquery
Statements(#): 1
Source Tables:
    be_dataset.order
    be_dataset.tb_order
Target Tables:
    target.order
```

**Comment by duongphannamhung** [comment]
Thanks for your reply, I have a replacement "`" before parsing in sqllineage, will re-open if I found this problem again.
