### ISSUE TITLE
Missing Source Table for MERGE statement when UNION involved in source subquery

### ISSUE THREAD

**Issue by entilo** [reata/sqllineage#406]
version: sqllineage 1.4.2 

when i use LineageRunner to parse sql below, it turned out error like:"return name.strip("`").strip('"').strip("'") AttributeError: 'NoneType' object has no attribute 'strip'":

create or replace view scn.vwn as
SELECT 1 as file_type
FROM scn.tbn

LineageRunner parse error

**Comment by entilo** [comment]
error sql:
create or replace view scn.vwn as
SELECT 1 as file_type
FROM scn.tbn

correct sql:
create or replace view scn.vwn as
SELECT 1 file_type
FROM scn.tbn

there is something wrong with the "as", i dont konw why

**Comment by reata** [comment]
This happens only with default non-validating dialect, where sqlparse defines FILE_TYPE as a builtin data type, thus not allowed as alias name. 

Can you try switch to ansi dialect? In the long run, we will deprecate non-validating support.

**Comment by entilo** [comment]
您好，邮件已收到，祝您天天好心情！

**Comment by reata** [comment]
Can you try upgrading in v1.4.5? I believe this is already fixed.

**Comment by entilo** [comment]
> Can you try upgrading sqllineage to v1.4.5? I believe this is already fixed.
sqllineage 1.4.5 用下面sql进行解析有问题：
merge into tb_report_risk_day t using (
select * from (
select * from taba a
union all
select * from tabb b
)tb
inner join ext_tab et on tb.aaa = et.aaa)
s on (t.cpdm = s.vc_cpdm) when matched then update set t.upd = s.upd;


LineageRunner(sql=veryfy_sql)
源表为:[Table: <default>.ext_tab, Table: <default>.taba, Table: <default>.tabb]
目标表为: <default>.tb_report_risk_day

LineageRunner(sql=veryfy_sql, dialect="ansi")
源表为:[]
目标表为: <default>.tb_report_risk_day


LineageRunner方言模式没有报错，但是解析错误 ==

**Comment by reata** [comment]
I can this is a bug that we need to fix. This is related to UNION ALL in source subquery.

**Comment by reata** [comment]
I did some research and this test case can be simplified to
```sql
SELECT *
FROM (SELECT *
      FROM foo
      UNION ALL
      SELECT *
      FROM bar) s1
         CROSS JOIN baz
```
where ANSI dialect still has problem identifying all source table correctly, it only recognizes baz.
