### ISSUE TITLE
Update `sqlfluff` dependency to latest one

### ISSUE THREAD

**Issue by KulykDmytro** [reata/sqllineage#408]
There are many changes happen on `sqlfluff` since version 2.0.3 pinned in sqllineage

Is there a possibility to pin dependency to latest one? (2.1.2)

**Comment by reata** [comment]
We pinned sqlfluff to v2.0.3 as v2.0.4 breaks some test cases related to `LATERAL VIEW explode` syntax.

If that is fixed in latest sqlfluff, we can certainly upgrade. Otherwise we need a more compelling reason for upgrade.

**Comment by reata** [comment]
Submitted a PR(https://github.com/sqlfluff/sqlfluff/pull/4980) to sqlfluff to fix the `LATERAL VIEW` issue. In particular, when there're multiple column aliases like our failed test case `LATERAL VIEW json_tuple(sc.json, 'key1', 'key2') q AS item0, item1`, all the column alias except the first one, will be parsed as from_expression, which breaks our table level lineage.

Once that's merged and released, we can upgrade sqlfluff dependency to be >= next version. @KulykDmytro Let me know if you're interested in following up on this. We also need to get other failed test cases fixed, but the good news is that all the rest failed ones are limited to change on sqllineage code base only.

cc @nahuelverdugo for awareness.

**Comment by reata** [comment]
All the changes we needed are merged to sqlfluff and release as of v2.1.4. We can now upgrade to that version and solving other issues at the same time.
