### ISSUE TITLE
Dialect='tsql' should return warning when no semicolons are detected

### ISSUE THREAD

**Issue by crossxwill** [reata/sqllineage#422]
The issue is related to #384 and #159. It's common (although frustrating) practice to **exclude** semicolons in TSQL queries. For example:

```sql
-- sample_query.sql

SELECT CUST_ID, CUST_NAME, CUST_CITY, CUST_COUNTRY
INTO #TEMP_CUSTOMERS
FROM T_CUSTOMERS
WHERE CUST_COUNTRY = 'USA'

SELECT CUST.*
    , SALES.CUM_SALES
INTO #TEMP_FINAL_RESULTS
FROM #TEMP_CUSTOMERS CUST AS CUST
LEFT JOIN T_SALES AS SALES
ON CUST.CUST_ID = SALES.CUST_ID
WHERE SALES.CUST_ID IS NULL

SELECT *
FROM #TEMP_FINAL_RESULTS

```

This causes the `LineageRunner()` to parse the first statement and skip the remaining statements.

```python
from sqllineage.runner import LineageRunner
import csv
import pandas as pd

# read text from sample_query.sql
sql_script = open('sample_query.sql', 'r').read()

# parse sql_script with LineageRunner
parsed_results = LineageRunner(sql_script, dialect="tsql")

# write parsed_results to data frame
df = pd.DataFrame(parsed_results.get_column_lineage())

df.columns = ['Source', 'Target']

print(df)
```

The output is:

Source                |                  Target
----------|----------
`<default>.t_customers.cust_city`  |   `<default>.#temp_customers.cust_city`
`<default>.t_customers.cust_country` | `<default>.#temp_customers.cust_country`
`<default>.t_customers.cust_id`      | `<default>.#temp_customers.cust_id`
`<default>.t_customers.cust_name`   |  `<default>.#temp_customers.cust_name`

The proposal is to return a warning message when `dialect='tsql'`:

```python
parsed_results = LineageRunner(sql_script, dialect="tsql")

"""Warning: No semicolons detected. Consider adding a semicolon after each statement."""
```

**Comment by reata** [comment]
Adding a warning is easy. Though I'm not familiar with tsql enough. Does split it to multiple statements make sense?

**Comment by crossxwill** [comment]
I suggest adding the warning message. I'm not familiar with how Microsoft parses multiple statements without a semicolon.

**Comment by reata** [comment]
A SyntaxWarning will be triggered in case like this. We'll handle split statements without semicolon in #384
