### ISSUE TITLE
Support subquery in VALUES clause

### ISSUE THREAD

**Issue by entilo** [reata/sqllineage#432]
from sqllineage.runner import LineageRunner

veryfy_sql= "INSERT INTO taba (a1, b1) VALUES (1,(SELECT max(bb) FROM tabb ));"
analysis_result = LineageRunner(sql=veryfy_sql, dialect="ansi")
logging.info(f'source_tables: {analysis_result.source_tables}')

as mentioned above，sourcetables is empty，is this need to be fixed？

**Comment by entilo** [comment]
sqlline version is 1.4.5

**Comment by reata** [comment]
This is the first time I saw a SQL with subquery in VALUES clause. Never even imagine this is allowed. So it's only natural that we don't have analyzing logic targeting this. We can add support for it. This should be an easy one.

By the way, can you share the actual SQL dialect/database that you're running this SQL with?
