### ISSUE TITLE
Incorrect source recognition

### ISSUE THREAD

**Issue by Aka-shi** [reata/sqllineage#449]
For the query 
`insert into db.table1 (
select x.id
FROM table2 x
)` 
sqllineage -f query.sql gives the following output
```
Statements(#): 1
Source Tables:

Target Tables:
    db.table1
```

But for query `insert into table1 (
select x.id
FROM table2 x
)`
It gives the correct output
```
Statements(#): 1
Source Tables:
    <default>.table2
Target Tables:
    <default>.table1
```

Is this a bug or am I missing anything?

**Comment by reata** [comment]
This is a known issue for default non-validating dialect that we won't be able to fix due to parser issue.

Please use ansi dialect instead. `sqllineage -f query.sql --dialect=ansi`
