### ISSUE TITLE
Parser looks like ignoring column named Version

### ISSUE THREAD

**Issue by Ricardop1** [reata/sqllineage#450]
Hi!
Looks like when a column is named Version, the parser ignores it. 
For example, for the query:

'Create VIEW Database.Example2 AS SELECT Date, Family, Version, Version_test FROM Database.Example;'

The parser will return all relations and columns successfully except for the column named Version that is ignored.
Could it be that Version is a Keyword and can't be used or could it be a bug?

sqllineage version is 1.4.6

**Comment by reata** [comment]
What's the dialect you're using? The default non-validating dialect cannot handle KEYWORD very well.

Please use ansi instead:
```shell
➜  ~ sqllineage -e "Create VIEW Database.Example2 AS SELECT Date, Family, Version, Version_test FROM Database.Example;" -l column --dialect=ansi
database.example2.date <- database.example.date
database.example2.family <- database.example.family
database.example2.version <- database.example.version
database.example2.version_test <- database.example.version_test
```

**Comment by reata** [comment]
Close as no further response.
