### ISSUE TITLE
The problem with the column lineage for repeated aliases

### ISSUE THREAD

**Issue by kkozhakin** [reata/sqllineage#451]
Hi! 

There was a problem with building a column lineage due to repeated aliases, in which it is impossible to uniquely correlate paths.

For example, for the query:
```sql
CREATE TEMPORARY TABLE "phone_pd_cur" ON COMMIT DROP AS

SELECT "a1"."phone_pd_id" as "phone_pd_id"
  , "h"."id"
  , "h"."utc_valid_from_dttm"
FROM (
  SELECT t.id
    , t.utc_valid_from_dttm

  FROM (SELECT * FROM "schema1"."h__phone_pd") as t) as h

  LEFT JOIN (SELECT * FROM "schema1"."a__phone_pd__phone_pd_id__key") as "a1"
            ON "a1".id = h.id

DISTRIBUTED RANDOMLY;
ANALYZE "phone_pd_cur";
CREATE TEMPORARY TABLE "email_pd_cur" ON COMMIT DROP AS

SELECT "a1"."email_pd_id" as "email_pd_id"
  , "h"."id"
  , "h"."utc_valid_from_dttm"
FROM (
  SELECT t.id
    , t.utc_valid_from_dttm

  FROM (SELECT * FROM "schema1"."h__email_pd") as t) as h

  LEFT JOIN (SELECT * FROM "schema1"."a__email_pd__email_pd_id__key") as "a1"
            ON "a1".id = h.id

DISTRIBUTED RANDOMLY;
ANALYZE "email_pd_cur";
```
column lineage is:
```
<default>.email_pd_cur.email_pd_id <- a1.email_pd_id
<default>.email_pd_cur.id <- h.id <- t.id
<default>.email_pd_cur.utc_valid_from_dttm <- h.utc_valid_from_dttm <- t.utc_valid_from_dttm
<default>.phone_pd_cur.id <- h.id <- t.id
<default>.phone_pd_cur.phone_pd_id <- a1.phone_pd_id
<default>.phone_pd_cur.utc_valid_from_dttm <- h.utc_valid_from_dttm <- t.utc_valid_from_dttm
a1.* <- schema1.a__email_pd__email_pd_id__key.*
a1.* <- schema1.a__phone_pd__phone_pd_id__key.*
t.* <- schema1.h__email_pd.*
t.* <- schema1.h__phone_pd.*
```

**Comment by reata** [comment]
Can you share the sqllineage version, dialect and expected result?

**Comment by kkozhakin** [comment]
Version: 1.3.8 (but on 1.4.7 the same problem)
Dialect: no (with dialect greenplum or postgresql doesn't work)

Expected result:

<default>.email_pd_cur.email_pd_id <- schema1.a__email_pd__email_pd_id__key.email_pd_id
<default>.email_pd_cur.id <- h.id <- schema1.h__email_pd.id
<default>.email_pd_cur.utc_valid_from_dttm <- h.utc_valid_from_dttm <- schema1.h__email_pd.utc_valid_from_dttm
<default>.phone_pd_cur.id <- h.id <- schema1.h__phone_pd.id
<default>.phone_pd_cur.phone_pd_id <- schema1.a__phone_pd__phone_pd_id__key.phone_pd_id
<default>.phone_pd_cur.utc_valid_from_dttm <- h.utc_valid_from_dttm <- schema1.h__phone_pd.utc_valid_from_dttm

or

<default>.email_pd_cur.email_pd_id <- a1_hash1.email_pd_id
<default>.email_pd_cur.id <- h.id <- t_hash3.id
<default>.email_pd_cur.utc_valid_from_dttm <- h.utc_valid_from_dttm <- t_hash3.utc_valid_from_dttm
<default>.phone_pd_cur.id <- h.id <- t_hash4.id
<default>.phone_pd_cur.phone_pd_id <- a1_hash2.phone_pd_id
<default>.phone_pd_cur.utc_valid_from_dttm <- h.utc_valid_from_dttm <- t_hash4.utc_valid_from_dttm
a1_hash1.* <- schema1.a__email_pd__email_pd_id__key.*
a1_hash2.* <- schema1.a__phone_pd__phone_pd_id__key.*
t_hash3.* <- schema1.h__email_pd.*
t_hash4.* <- schema1.h__phone_pd.*

**Comment by reata** [comment]
It's a lot of things combined in this case, let me explain one by one:

1. greenplum dialect is not supported by us, the closest thing is postgres, while postgres doesn't support "DISTRIBUTED RANDOMLY", which is greenplum specific grammar. Upstream parser lib sqlfluff doesn't support greenplum at the moment. So non-validating is the only choice. But we're deprecating non-validating in future release.
2. If we remove "DISTRIBUTED RANDOMLY" and use postgres, then UnsupportedStatementException will be raised, because "SQLLineage doesn't support analyzing statement type [analyze_statement]". This is something sqllineage should fix.
3. If we further remove "ANALYZE" statement, then we get the same output using postgres as non-validating. This is related to inferring column from `SELECT *`, which we plan to support. You can watch #303 for future update.

**Comment by reata** [comment]
analyze_statement support is added. Close this as duplicate.

**Comment by reata** [comment]
greenplum is actually supported since sqlfluff v2.0.3, sorry for the misleading information above. We should work with sqlfluff community to get `DISTRIBUTED RANDOMLY` syntax supported then.

**Comment by kkozhakin** [comment]
Hi! Another problem for this issue.
For the query:
```
                        CREATE TEMPORARY TABLE temp_table_2 ON COMMIT DROP AS
                        SELECT t.field_1 as field_1
                        FROM (select * from "schema_0"."table_2") t;

                        CREATE TEMPORARY TABLE result_table ON COMMIT DROP AS
                        SELECT t.field_1 AS field_1,
                        tmp2.field_1 as field_2
                        FROM (select * from "schema_0"."table_1") t
                            LEFT JOIN (select * from temp_table_2) tmp2
                                ON t.field_1 = tmp2.field_1
                        ;

                        INSERT INTO "schema_1"."table_1" (
                               "field_1"
                             , "field_2"
                        )
                        SELECT "field_1"
                             , "field_2"
                        FROM "pg_temp_1"."result_table";
```
column lineage is:
```
<default>.result_table.field_1 <- t.field_1
<default>.result_table.field_2 <- tmp2.field_1
<default>.temp_table_2.field_1 <- t.field_1
schema_1.table_1.field_1 <- <default>.result_table.field_1
schema_1.table_1.field_2 <- <default>.result_table.field_2
t.* <- schema_0.table_1.*
t.* <- schema_0.table_2.*
tmp2.* <- <default>.temp_table_2.*
```
but if you look at the classes, then it considers `schema_0.table_2` to be the parent of alias `t` in first row. However, this is not correct.

**Comment by reata** [comment]
`DISTRIBUTED RANDOMLY` is now supported with greenplum dialect in sqllineage v1.4.8 by upgrading sqlfluff to v2.3.3
