### ISSUE TITLE
HQL (Hibernate Query Language) Lineage Graphing

### ISSUE THREAD

**Issue by matanitah** [reata/sqllineage#461]
Hi,
I am trying to implement a program which graphs the source and target tables for a number of different .hql files. However, when I run LineageRunner(f.read(), 'non-validating'), there are missing source tables for certain target tables. How can I get the complete set of source tables? Is there some programmatic way for me translate hql to sql in python?
Thanks for any help!

**Comment by matanitah** [comment]
Note: when I open the graph using the -g flag I find the missing source tables in the graph but there is no arrow between them and the target table.

**Comment by reata** [comment]
Please share the SQL and expected result so we can help.

**Comment by reata** [comment]
Close as no further response.
