### ISSUE TITLE
variables in hql

### ISSUE THREAD

**Issue by Tab-ome** [reata/sqllineage#463]
**Describe the bug**
* Variable problem in hql

**SQL**
```sql
create table a_${month_id}  as select * from b;
```

For example:
```python
from sqllineage.runner import LineageRunner
result = LineageRunner('create table a_${month_id}  as select * from b;', dialect="hive")
print(result.target_tables)
```

**Python version (available via `python --version`)**

 - 3.11.5

**SQLLineage version (available via `sqllineage --version`):**
 - 1.4.7

**Additional context**
There are variables in sql, but they cannot be parsed. Is it possible to process the special characters contained in sql?

**Comment by Tab-ome** [comment]
hive sql in shell.

**Comment by reata** [comment]
This is expected as sql with variables is not runnable. Hive internally needs to substitute the variable with actual values running it. Here's the reference:
- https://cwiki.apache.org/confluence/display/Hive/LanguageManual+VariableSubstitution
- https://github.com/apache/hive/blob/master/common/src/java/org/apache/hadoop/hive/conf/VariableSubstitution.java

For the moment, we don't have plans to support variables substitution. So you should take care of the variables and call sqllineage with runnable sql.
