### ISSUE TITLE
Optimization function identification

### ISSUE THREAD

**Issue by LDJszz** [reata/sqllineage#506]
Unable to recognize some functions

example：
drop table if exists tmp_db.tme_01;
create table tmp_db.tme_01 stored as parquet as
select
       t1.hid
       ,t1.day1 
	   ,t1.total_re 
	   ,t1.rr 
	   ,t1.mr  
	   ,t1.rn  
	   ,t2.rers  
	   ,coalesce(t1.rr / t2.rers,0) as room_RevPAR 
	   ,coalesce(t1.total_re / t2.rers,0) as combined_RevPAR  
	   ,coalesce(t1.rn / t2.rers,0) as combined_rental_rate  
from
    (select
			hid  
			,day1 
			,total_re  
			,re as rr 
			,mr  
			,rn  
        from bi_dw.dwd_t1  
        where datekey='${v_bthDate}'
        ) t1
left join(SELECT
                 hid  
				 ,day1  
				 ,res as rers  
                FROM  bi_dw.dwd_t2 
                where datekey='${v_bthDate}'
                ) t2
on t1.hid = t2.hid and t1.day1 = t2.day1;

![fun](https://github.com/reata/sqllineage/assets/33858113/31fd94ce-2a82-423a-932f-e636f8a81508)

**Comment by reata** [comment]
this is a known issue with non-validating dialect, which we're looking at deprecation in future releases. So we won't fix this, you're welcome to switch to sparksql or hive dialect.

Reference: #325
