### ISSUE TITLE
Support Change Configure Default Schema At Runtime

### ISSUE THREAD

**Issue by reata** [reata/sqllineage#536]
Continue on the undone feature on #523.

#523 add an environment variable to configure default schema. That solves part of the problem but it would still be preferable if we can support configure through LineageRunner.

Create this issue to continue tracking on that.

**Comment by delphisharp** [comment]
最新 master的实现 无法正常完成功能。
因为 Schema init 函数 传入时已经完成变量绑定
我马上提交测试用例和修复PR

The latest master implementation cannot complete the function properly.
Because the variable binding has been completed when Schema init function is passed in
I will submit test cases and fix PR immediately

**Comment by reata** [comment]
We don't necessarily have to make it "configure through LineageRunner". It will be OK as long as we can let user update the configure at runtime.
