### ISSUE TITLE
"LATERAL VIEW EXPLODE_SPLIT" not supported!

### ISSUE THREAD

**Issue by expressways** [reata/sqllineage#546]
SELECT 
a.code,
mi,
we
FROM ods.ods_wbs_car_location_v a
LATERAL VIEW EXPLODE_SPLIT (materiel_id,',') b AS mi
LATERAL VIEW EXPLODE_SPLIT (weight,',') d AS we

**Comment by reata** [comment]
Can you share the sqllineage version, Python version and dialect you're using?

**Comment by reata** [comment]
Close as no further response.
