### ISSUE TITLE
Missing target table with tsql parsing into statements with union

### ISSUE THREAD

**Issue by 13011017515** [reata/sqllineage#562]
**Describe the bug**
* There is an issue with tsql parsing into statements with union, unable to obtain target

**SQL**
```sql
select * into t3 from t1 union all select * from t2
```

- `if` CLI (Command Line Interface): provide the command you're calling and the output. 
For example:
```shell
sqllineage -e 'select * into t3 from t1 union all select * from t2' -d tsql
```
```
Statements(#): 1
Source Tables:
    <default>.t2
    <default>.t3
Target Tables:
```

**Python version (available via `python --version`)**
 - 3.12.1

**SQLLineage version (available via `sqllineage --version`):**
 - 1.5.0

**Comment by reata** [comment]
The expected output should be:
```
Source Tables:
    <default>.t1
    <default>.t2
Target Tables:
    <default>.t3
```
Is that correct?

**Comment by 13011017515** [comment]
Yes, this is correct

**Comment by reata** [comment]
Thanks for your confirmation. Looks like we have some issue in handling SELECT INTO + UNION case.

**Comment by 13011017515** [comment]
麻烦帮忙修复嘛，这对我真的很重要 0.0。
可以在这里请教一个问题嘛，对于SQL server存储过程的解析，我使用时，不能直接解析，需要去掉create ...  begin ... 之后，只保留sql，才可以。怎样可以直接解析，或者忽略掉 create ..... begin ... 语句，silent_mode = True，添加了，也无法解析.....

**Comment by maoxingda** [comment]
You need to do preprocessing yourself, because [sqlfluff](https://github.com/sqlfluff/sqlfluff) does not support stored procedures, not sqllineage.

**Comment by 13011017515** [comment]
ok
