### ISSUE TITLE
I hope to add the lineage of flink sql

### ISSUE THREAD

**Issue by projoy** [reata/sqllineage#570]
sqllineage is very simple to use and very  powerful, very good, thank you very much for your efforts!!!

In sqllineage, I see support for spark sql, but not flink sql.

At present, flink sql is also used very widely, can you add a support for flink sql?

Thank you very much!

**Comment by maoxingda** [comment]
The issue should be mentioned in the [SQLFluff](https://github.com/sqlfluff/sqlfluff) community instead of here.

**Comment by projoy** [comment]
OK, I get it. Thank you!
