### ISSUE TITLE
Unable to accurately parse the specified fields after the insert into table

### ISSUE THREAD

**Issue by vshunter** [reata/sqllineage#574]
EG：insert into db1.tab1(x,y,z ) select a,b,c from db2.tab2
actual  result:
db1.tab1.a <- db2.tab2.a
db1.tab1.b <- db2.tab2.b
db1.tab1.c <- db2.tab2.c

expected result:
db1.tab1.x <- db2.tab2.a
db1.tab1.y <- db2.tab2.b
db1.tab1.z <- db2.tab2.c

**Comment by reata** [comment]
just released v1.5.1 and you can upgrade the latest version.
