### ISSUE TITLE
[hive-dialect] dbName . tableName can not work failed

### ISSUE THREAD

**Issue by zhengtingxue** [reata/sqllineage#605]
bad_sql;
insert into table table_a a . field1,field2 from dbName.     sourceTable; 
sqllineage work failed,but hive work succ

**Comment by delphisharp** [comment]
You can write a hook function based on hive to obtain the parsing plan. If only for Hive.
example :https://github.com/thestyleofme/data-lineage-parent/blob/master/lineage-hooks/lineage-hive-hook/README.md

**Comment by zhengtingxue** [comment]
thanks
