### ISSUE TITLE
Cartesian product exception with ANSI-89 Syntax

### ISSUE THREAD

**Issue by coldmoutain** [reata/sqllineage#89]
when i use LineageRunner to analyze a sql string like "select a.* from table a,table  b "   it throws a  SQLLineageException:
SQLLineageException: An Identifier is expected, got IdentifierList[value:  a, table] instead 
So how can i deal with that exception? 

`from sqllineage.runner  import *
LineageRunner("select a.* from table1 a, table2 b").target_tables`

`---------------------------------------------------------------------------
SQLLineageException                       Traceback (most recent call last)
<ipython-input-102-0715be0fec21> in <module>()
----> 1 LineageRunner("select a.* from table1 a, table2 b").target_tables

~/anaconda3/lib/python3.6/site-packages/sqllineage/runner.py in __init__(self, sql, encoding, verbose)
     31             if s.token_first(skip_cm=True)
     32         ]
---> 33         self._lineage_results = [LineageAnalyzer().analyze(stmt) for stmt in self._stmt]
     34         self._combined_lineage_result = combine(*self._lineage_results)
     35         self._verbose = verbose

~/anaconda3/lib/python3.6/site-packages/sqllineage/runner.py in <listcomp>(.0)
     31             if s.token_first(skip_cm=True)
     32         ]
---> 33         self._lineage_results = [LineageAnalyzer().analyze(stmt) for stmt in self._stmt]
     34         self._combined_lineage_result = combine(*self._lineage_results)
     35         self._verbose = verbose

~/anaconda3/lib/python3.6/site-packages/sqllineage/core.py in analyze(self, stmt)
     91         else:
     92             # DML parsing logic also applies to CREATE DDL
---> 93             self._extract_from_DML(stmt)
     94         return self._lineage_result
     95 

~/anaconda3/lib/python3.6/site-packages/sqllineage/core.py in _extract_from_DML(self, token)
    143                         raise SQLLineageException(
    144                             "An Identifier is expected, got %s[value: %s] instead"
--> 145                             % (type(sub_token).__name__, sub_token)
    146                         )
    147                     source_table_token_flag = False

SQLLineageException: An Identifier is expected, got IdentifierList[value: table1 a, table2 b] instead`

**Comment by reata** [comment]
Hi @coldmoutain , to do a cartesian join in ANSI-92 standard SQL, it's more like
```
select a.* from table1 a cross join table2 b
```
or simply join without on condition
```
select a.* from table1 a join table2 b
```

As for the syntax you're using, I look it up a little bit. It seems this is ANSI-89 standard. Personally I've never seen it before. Would you mind tell me which SQL dialect you are using? Is it Oracle?

**Comment by coldmoutain** [comment]
Hello @reata , I read the  stackoverflow question your provided,  According to the question , my SQL is   ANSI-89 standard. 
well ,i am using MYSQL ,  in my group ,most of workmate  use the ANSI-89 standard . so a great number of SQL are using " , "  instead of "cross join" (or  join).even  in HQL  .  so can the sqllineage deal with  that problem? if it can ,what should i do .

**Comment by reata** [comment]
It's not supported yet. I'll take a look to see what I can do to make it work.

**Comment by coldmoutain** [comment]
well ,I have  tried some  methods to make it work  but didn`t work  well ,.if you  solve   it .notices me pleases

**Comment by reata** [comment]
It's fixed in master branch. Plan to release v1.0.2 this weekend.

**Comment by coldmoutain** [comment]
thx!
